args <- commandArgs(trailingOnly = FALSE)
file_arg <- "--file="
script_path <- sub(file_arg, "", args[grep(file_arg, args)])
script_dir <- dirname(normalizePath(script_path, winslash = "/", mustWork = FALSE))
project_root <- normalizePath(file.path(script_dir, ".."), winslash = "/", mustWork = TRUE)

read_utf8 <- function(...) {
  file_path <- file.path(project_root, ...)
  if (length(file_path) == 0 || !file.exists(file_path)) return("")
  paste(readLines(file_path, encoding = "UTF-8", warn = FALSE), collapse = "\n")
}
database_manager_text <- read_utf8("modules", "database_manager.R")
if (!nzchar(database_manager_text)) return(invisible(NULL))
readme_text <- read_utf8("README.md")
guide_text <- read_utf8("PROJECT_GUIDE.md")
spec_text <- read_utf8("PROJECT_SPEC.md")
deployment_text <- read_utf8("DEPLOYMENT_GUIDE.md")
compose_local_text <- read_utf8("docker-compose.local.yml")
compose_temp_text <- read_utf8("docker-compose1.yml")
compose_server_text <- read_utf8("docker-compose.server.yml")
env_example_text <- read_utf8("deploy", "alicloud", "env", ".env.example")
test_env_example_text <- read_utf8(".env.test.example")

expect_contains <- function(text, pattern, label) {
  if (!grepl(pattern, text, perl = TRUE)) {
    stop(sprintf("缺少预期内容: %s", label), call. = FALSE)
  }
}

expect_not_contains <- function(text, pattern, label) {
  if (grepl(pattern, text, perl = TRUE)) {
    stop(sprintf("发现应移除内容: %s", label), call. = FALSE)
  }
}

expect_contains(database_manager_text, "从服务器目录导入数据空间", "数据库管理模块导入入口文案")
expect_contains(database_manager_text, "请输入服务器或容器可见的绝对路径", "数据库管理模块导入占位提示")
expect_contains(database_manager_text, "当前仅支持导入部署机器可见目录，不支持直接读取浏览器所在电脑的本地文件夹。", "数据库管理模块导入边界说明")
expect_contains(database_manager_text, "该入口当前仅面向系统管理员开放；多用户能力落地前不面向普通用户开放。", "数据库管理模块管理员限定说明")
expect_contains(database_manager_text, "service_create_workspace\\(", "数据库管理模块通过 service 创建 workspace")
expect_contains(database_manager_text, "service_delete_workspace\\(", "数据库管理模块通过 service 删除 workspace")
expect_contains(database_manager_text, "当前账号无权管理该数据空间", "数据库管理模块 workspace 管理权限提示")
expect_contains(database_manager_text, "数据库管理功能尚未开放，请联系系统管理员授权", "数据库管理模块数据库锁提示")
expect_contains(database_manager_text, "db_access_enabled", "数据库管理模块依赖数据库管理权限字段")
expect_contains(database_manager_text, "title = \"数据空间工作台\"", "数据库管理模块阶段二主标题")
expect_contains(database_manager_text, "\"空间与目录\"", "数据库管理模块阶段二空间与目录标签")
expect_contains(database_manager_text, "\"上传与导入\"", "数据库管理模块阶段二上传与导入标签")
expect_contains(database_manager_text, "\"结构总览\"", "数据库管理模块阶段二结构总览标签")
expect_not_contains(database_manager_text, "从本地文件夹导入数据空间", "数据库管理模块旧导入文案")

expect_contains(readme_text, "当前 `/app/` 已实现应用内自注册、登录、退出与 workspace 级权限过滤。", "README 访问控制边界")
expect_contains(readme_text, "登录与注册已拆为两个页面，并改为上下居中的单列卡片布局；登录支持用户名或邮箱，注册会采集邮箱并做格式校验，但暂未接入真实邮箱验证。", "README 登录注册说明")
expect_contains(readme_text, "认证主体区域已抽到 `auth_manager.R`；当前用户信息、退出入口与普通用户的“权限管理”快捷入口已合并到侧边栏卡片中。", "README 认证模块与侧边栏信息")
expect_contains(readme_text, "未登录状态下仅显示登录/注册入口；进入工作台前不展示业务侧边栏。", "README 未登录入口说明")
expect_contains(readme_text, "当前工具声明为：不负责数据安全、数据传到服务不保证安全，请使用方自行妥善保管数据；如需更高保障，可提供独立部署服务。", "README 免责声明")
expect_contains(readme_text, "且该入口只面向系统管理员开放。", "README 管理员限定")
expect_contains(readme_text, "当前系统角色口径仅保留系统管理员与普通用户", "README 角色口径")
expect_contains(readme_text, "不得读取、浏览或导出其他用户数据空间中的实际数据", "README 服务层保密底线")
expect_contains(readme_text, "管理员账号必须通过环境变量预置 `APP_ADMIN_USERNAME`、`APP_ADMIN_EMAIL` 与 `APP_ADMIN_PASSWORD`；未配置时不自动提升首个注册用户。", "README 管理员环境变量说明")
expect_contains(readme_text, "workspace、membership、invite 与 owner 迁移能力已统一下沉到 service 层。", "README service 层说明")
expect_contains(readme_text, "workspace 创建与删除也统一复用 `account_service.R`", "README workspace service 收口说明")
expect_contains(readme_text, "普通用户可对自己拥有的数据空间进行权限管理，且授权、撤销与 owner 迁移统一通过邮箱输入完成", "README Owner 邮箱授权说明")
expect_contains(readme_text, "管理员页保持独立系统入口，不并入侧边栏用户卡片", "README 管理员入口独立说明")
expect_contains(readme_text, "管理员页现补充信息型增强：顶部系统概览、运行环境摘要、目标账号完整状态卡片、操作影响预览，以及“我名下数据空间概览”", "README 管理员信息增强说明")
expect_contains(readme_text, "管理员页前端展示现按“摘要优先、明细随后”收拢", "README 管理员前端收拢说明")
expect_contains(readme_text, "账号状态管理已与“所有注册账号总览”联动", "README 管理员账号状态联动说明")
expect_contains(readme_text, "管理员页现已补充“异常态势摘要”", "README 管理员异常态势摘要说明")
expect_contains(readme_text, "异常态势摘要现支持页内快捷跳转，可直接定位到账号状态管理、负责人调整、协作授权与我名下数据空间概览；跳转后会聚焦对应输入框，并在协作相关场景切换到相关预览 tab", "README 管理员异常态势摘要快捷跳转说明")
expect_contains(readme_text, "管理员页现已补充“所有注册账号总览”，通过摘要卡、预设筛选按钮与总览表结合的方式展示所有已注册账号的元信息", "README 管理员注册账号总览说明")
expect_contains(readme_text, "权限预览表与管理员 membership 预览表已改为面向业务的中文列名", "README 预览表中文列名说明")
expect_contains(readme_text, "数据库管理页已按“空间与目录 / 上传与导入 / 结构总览”三段重组", "README 数据库管理阶段二布局")
expect_contains(readme_text, "数据库管理功能已增加账号级访问锁", "README 数据库管理锁说明")
expect_contains(readme_text, "未开通数据空间功能的普通用户登录后默认落到“数据准备”页", "README 未开通数据空间功能默认落点")
expect_contains(readme_text, "普通用户在未开通数据空间功能时，只允许单文件临时上传；该数据仅用于当前会话分析，不写入持久化数据空间", "README 临时上传说明")
expect_contains(readme_text, "当前阶段风险与优化建议", "README 风险与优化建议章节")
expect_contains(readme_text, "tests/test_auth_access_postgres_integration.R", "README PostgreSQL 集成测试文件")
expect_contains(readme_text, "tests/test_admin_manager_smoke_shinytest2.R", "README 管理员页 shinytest2 smoke test 文件")
expect_contains(readme_text, "run_auth_regression.ps1", "README 账号模块统一回归入口")
expect_contains(readme_text, "工具链建议：在现有 `tests/` 守卫测试之外持续维护基于 PostgreSQL 测试库的自动化回归", "README 工具链建议")
expect_contains(readme_text, "docker-compose.local.yml` 或 `docker-compose1.yml`", "README 测试端口说明")
expect_contains(readme_text, "`docker-compose.local.yml` 现直接读取 `.env.test`", "README local compose 读取 .env.test")
expect_contains(readme_text, "docker-compose1.yml` 当前收口为轻量测试基础设施栈", "README compose1 轻量测试基础设施说明")

expect_contains(guide_text, "当前仓库已实现应用内自注册、登录、退出与 workspace 级权限控制。", "PROJECT_GUIDE 访问控制边界")
expect_contains(guide_text, "登录支持用户名或邮箱；注册阶段会校验邮箱格式，当前登录/注册页已改为上下居中的单列卡片布局，但尚未接入真实邮箱验证或邮件发送。", "PROJECT_GUIDE 邮箱说明")
expect_contains(guide_text, "当前用户信息与退出入口稳定显示在侧边栏卡片中；普通用户的权限管理快捷入口也合并在该卡片内。", "PROJECT_GUIDE 侧边栏信息")
expect_contains(guide_text, "未登录状态下只渲染登录/注册入口，不渲染业务工作台侧边栏。", "PROJECT_GUIDE 未登录入口说明")
expect_contains(guide_text, "当前系统角色口径仅保留系统管理员与普通用户。", "PROJECT_GUIDE 角色口径")
expect_contains(guide_text, "可查看数据库信息与 workspace 元信息，但不得读取、浏览或导出其他用户数据空间中的实际数据", "PROJECT_GUIDE 管理员能力")
expect_contains(guide_text, "当前工具暂不负责数据安全；数据传到服务端后不保证安全，请使用方自行妥善保管数据。", "PROJECT_GUIDE 免责声明-安全")
expect_contains(guide_text, "管理员账号必须通过环境变量预置 `APP_ADMIN_USERNAME`、`APP_ADMIN_EMAIL` 与 `APP_ADMIN_PASSWORD`；未配置时不自动提升首个注册用户。", "PROJECT_GUIDE 管理员环境变量说明")
expect_contains(guide_text, "服务器目录导入只面向系统管理员开放；在多用户能力真正落地前，不应向普通用户开放该入口。", "PROJECT_GUIDE 管理员限定")
expect_contains(guide_text, "当前仓库尚未实现 ZIP 数据空间导入；文档与功能描述不得把该能力写成已支持。", "PROJECT_GUIDE ZIP 未落地说明")
expect_contains(guide_text, "当前已支持用户自注册，并保留系统管理员账号。", "PROJECT_GUIDE 自注册目标")
expect_contains(guide_text, "当前首期隔离粒度以“个人空间”为主，每个用户默认拥有独立数据空间边界。", "PROJECT_GUIDE 个人隔离目标")
expect_contains(guide_text, "数据权限首期落到 workspace 级别", "PROJECT_GUIDE workspace 权限目标")
expect_contains(guide_text, "普通用户在未开通数据空间功能时，只允许单文件临时上传；上传数据仅用于当前会话分析，不写入持久化数据空间。", "PROJECT_GUIDE 临时上传说明")
expect_contains(guide_text, "`account_service.R`", "PROJECT_GUIDE 服务层文件")
expect_contains(guide_text, "`auth.R`", "PROJECT_GUIDE 认证共享层文件")
expect_contains(guide_text, "`auth_manager.R`", "PROJECT_GUIDE 认证页面模块文件")
expect_contains(guide_text, "`workspace_access_manager.R`", "PROJECT_GUIDE Owner 权限管理模块文件")
expect_contains(guide_text, "workspace 创建与删除也统一通过 `account_service.R` 收口", "PROJECT_GUIDE workspace service 收口说明")
expect_contains(guide_text, "普通用户可对自己拥有的数据空间进行权限管理，且授权、撤销与 owner 迁移统一通过邮箱输入完成。", "PROJECT_GUIDE Owner 邮箱授权说明")
expect_contains(guide_text, "管理员页保持独立系统入口，不并入侧边栏用户卡片", "PROJECT_GUIDE 管理员入口独立说明")
expect_contains(guide_text, "管理员页现补充信息型增强：顶部系统概览、运行环境摘要、目标账号完整状态卡片、操作影响预览，以及“我名下数据空间概览”", "PROJECT_GUIDE 管理员信息增强说明")
expect_contains(guide_text, "管理员页前端展示现按“摘要优先、明细随后”收拢", "PROJECT_GUIDE 管理员前端收拢说明")
expect_contains(guide_text, "账号状态管理已与“所有注册账号总览”联动", "PROJECT_GUIDE 管理员账号状态联动说明")
expect_contains(guide_text, "管理员页现已补充“异常态势摘要”", "PROJECT_GUIDE 管理员异常态势摘要说明")
expect_contains(guide_text, "异常态势摘要现支持页内快捷跳转，可直接定位到账号状态管理、负责人调整、协作授权与我名下数据空间概览；跳转后会聚焦对应输入框，并在协作相关场景切换到相关预览 tab", "PROJECT_GUIDE 管理员异常态势摘要快捷跳转说明")
expect_contains(guide_text, "管理员页现已补充“所有注册账号总览”，通过摘要卡、预设筛选按钮与总览表结合的方式展示所有已注册账号的元信息", "PROJECT_GUIDE 管理员注册账号总览说明")
expect_contains(guide_text, "权限预览表统一改为业务中文列名；数据库管理页按“空间与目录 / 上传与导入 / 结构总览”三段重组。", "PROJECT_GUIDE 阶段二 UI 说明")
expect_contains(guide_text, "数据库管理功能已增加账号级访问锁", "PROJECT_GUIDE 数据库管理锁说明")
expect_contains(guide_text, "未开通数据空间功能的普通用户登录后默认落到“数据准备”页", "PROJECT_GUIDE 未开通数据空间功能默认落点")
expect_contains(guide_text, "评估组织级、项目级隔离、邮箱验证与共享协作模型。", "PROJECT_GUIDE 多用户路线")
expect_contains(guide_text, "当前阶段风险与优化建议", "PROJECT_GUIDE 风险与优化建议章节")
expect_contains(guide_text, "管理员初始化必须通过环境变量预置；当前不支持用“首个注册用户自动升级”为系统管理员。", "PROJECT_GUIDE 初始化要求")
expect_contains(guide_text, "tests/test_auth_access_postgres_integration.R", "PROJECT_GUIDE PostgreSQL 集成测试文件")
expect_contains(guide_text, "tests/test_admin_manager_smoke_shinytest2.R", "PROJECT_GUIDE 管理员页 shinytest2 smoke test 文件")
expect_contains(guide_text, "在隔离 schema 中建表、验证和清理", "PROJECT_GUIDE PostgreSQL 集成测试策略")
expect_contains(guide_text, "run_auth_regression.ps1", "PROJECT_GUIDE 账号模块统一回归入口")
expect_contains(guide_text, "docker-compose.local.yml` 或 `docker-compose1.yml` 拉起 PostgreSQL，测试端口统一使用 `5432`", "PROJECT_GUIDE 测试端口说明")
expect_contains(guide_text, "`docker-compose.local.yml` 也直接读取 `.env.test`", "PROJECT_GUIDE local compose 读取 .env.test")
expect_contains(guide_text, "docker-compose1.yml` 当前定位为轻量测试基础设施栈", "PROJECT_GUIDE compose1 轻量测试基础设施说明")

expect_contains(spec_text, "当前系统角色仅保留系统管理员与普通用户两类。", "PROJECT_SPEC 角色口径")
expect_contains(spec_text, "不得读取、浏览或导出其他用户数据空间中的实际数据；该限制是服务层保密底线。", "PROJECT_SPEC 服务层保密底线")
expect_contains(spec_text, "普通用户未开通数据空间功能时，仅允许单文件临时上传；上传数据只用于当前会话分析，不写入持久化数据空间。", "PROJECT_SPEC 临时上传说明")
expect_contains(spec_text, "管理员初始化必须通过环境变量 `APP_ADMIN_USERNAME`、`APP_ADMIN_EMAIL`、`APP_ADMIN_PASSWORD` 预置，不支持首个注册用户自动升级。", "PROJECT_SPEC 管理员初始化")

expect_contains(deployment_text, "当前 `/app/` 已带应用层自注册、登录、退出与 workspace 级权限控制。", "DEPLOYMENT_GUIDE 访问控制边界")
expect_contains(deployment_text, "登录支持用户名或邮箱；注册阶段会保存邮箱并做格式校验，当前登录/注册页已改为上下居中的单列卡片布局，但尚未接入真实邮箱验证。", "DEPLOYMENT_GUIDE 邮箱说明")
expect_contains(deployment_text, "当前用户信息与退出入口稳定显示在侧边栏卡片中；普通用户的权限管理快捷入口也合并在该卡片内。", "DEPLOYMENT_GUIDE 侧边栏信息")
expect_contains(deployment_text, "未登录状态下仅显示登录/注册入口，不展示业务工作台侧边栏。", "DEPLOYMENT_GUIDE 未登录入口说明")
expect_contains(deployment_text, "且该入口应只对系统管理员开放。", "DEPLOYMENT_GUIDE 管理员限定")
expect_contains(deployment_text, "当前工具暂不负责数据安全；数据传到服务端后不保证安全，使用方需自行妥善保管数据。", "DEPLOYMENT_GUIDE 免责声明")
expect_contains(deployment_text, "当前系统角色口径仅保留系统管理员与普通用户；非管理员用户默认按个人空间隔离。", "DEPLOYMENT_GUIDE 角色口径")
expect_contains(deployment_text, "可查看数据库信息与 workspace 元信息，但不得读取、浏览或导出其他用户数据空间中的实际数据", "DEPLOYMENT_GUIDE 服务层保密底线")
expect_contains(deployment_text, "当前多用户实现为：支持自注册、保留系统管理员账号、默认按个人隔离", "DEPLOYMENT_GUIDE 多用户目标")
expect_contains(deployment_text, "管理员账号必须通过 `APP_ADMIN_USERNAME`、`APP_ADMIN_EMAIL` 与 `APP_ADMIN_PASSWORD` 预置；未配置时不自动提升首个注册用户。", "DEPLOYMENT_GUIDE 管理员环境变量说明")
expect_contains(deployment_text, "workspace、membership、invite 与 owner 迁移能力统一下沉到 service 层。", "DEPLOYMENT_GUIDE service 层说明")
expect_contains(deployment_text, "workspace 创建与删除也统一通过 `account_service.R` 收口", "DEPLOYMENT_GUIDE workspace service 收口说明")
expect_contains(deployment_text, "普通用户可对自己拥有的数据空间进行权限管理，且授权、撤销与 owner 迁移统一通过邮箱输入完成。", "DEPLOYMENT_GUIDE Owner 邮箱授权说明")
expect_contains(deployment_text, "管理员页保持独立系统入口，不并入侧边栏用户卡片", "DEPLOYMENT_GUIDE 管理员入口独立说明")
expect_contains(deployment_text, "管理员页现补充信息型增强：顶部系统概览、运行环境摘要、目标账号完整状态卡片、操作影响预览，以及“我名下数据空间概览”", "DEPLOYMENT_GUIDE 管理员信息增强说明")
expect_contains(deployment_text, "管理员页前端展示现按“摘要优先、明细随后”收拢", "DEPLOYMENT_GUIDE 管理员前端收拢说明")
expect_contains(deployment_text, "账号状态管理已与“所有注册账号总览”联动", "DEPLOYMENT_GUIDE 管理员账号状态联动说明")
expect_contains(deployment_text, "管理员页现已补充“异常态势摘要”", "DEPLOYMENT_GUIDE 管理员异常态势摘要说明")
expect_contains(deployment_text, "异常态势摘要现支持页内快捷跳转，可直接定位到账号状态管理、负责人调整、协作授权与我名下数据空间概览；跳转后会聚焦对应输入框，并在协作相关场景切换到相关预览 tab", "DEPLOYMENT_GUIDE 管理员异常态势摘要快捷跳转说明")
expect_contains(deployment_text, "管理员页现已补充“所有注册账号总览”，通过摘要卡、预设筛选按钮与总览表结合的方式展示所有已注册账号的元信息", "DEPLOYMENT_GUIDE 管理员注册账号总览说明")
expect_contains(deployment_text, "权限预览表统一改为业务中文列名；数据库管理页按“空间与目录 / 上传与导入 / 结构总览”三段重组。", "DEPLOYMENT_GUIDE 阶段二 UI 说明")
expect_contains(deployment_text, "数据库管理功能已增加账号级访问锁", "DEPLOYMENT_GUIDE 数据库管理锁说明")
expect_contains(deployment_text, "未开通数据空间功能的普通用户登录后默认落到“数据准备”页", "DEPLOYMENT_GUIDE 未开通数据空间功能默认落点")
expect_contains(deployment_text, "普通用户在未开通数据空间功能时，只允许单文件临时上传；上传数据仅用于当前会话分析，不写入持久化数据空间。", "DEPLOYMENT_GUIDE 临时上传说明")
expect_contains(deployment_text, "当前仓库未实现 ZIP 数据空间导入；部署说明和对外口径不得把该能力写成既成事实。", "DEPLOYMENT_GUIDE ZIP 未落地说明")
expect_contains(deployment_text, "当前阶段风险与优化建议", "DEPLOYMENT_GUIDE 风险与优化建议章节")
expect_contains(deployment_text, "`APP_ADMIN_USERNAME`", "DEPLOYMENT_GUIDE 管理员环境变量")
expect_contains(deployment_text, "`APP_ADMIN_EMAIL`", "DEPLOYMENT_GUIDE 管理员邮箱环境变量")
expect_contains(deployment_text, "tests/test_admin_manager_smoke_shinytest2.R", "DEPLOYMENT_GUIDE 管理员页 shinytest2 smoke test 文件")
expect_contains(deployment_text, "docker-compose.local.yml` 或 `docker-compose1.yml`", "DEPLOYMENT_GUIDE 测试端口说明")
expect_contains(deployment_text, "`docker-compose.local.yml` 现直接读取 `.env.test`", "DEPLOYMENT_GUIDE local compose 读取 .env.test")
expect_contains(deployment_text, "测试库应预留建 schema 权限", "DEPLOYMENT_GUIDE 集成测试 schema 权限")
expect_contains(deployment_text, "run_auth_regression.ps1", "DEPLOYMENT_GUIDE 账号模块统一回归入口")
expect_contains(compose_local_text, '5432:5432', "docker-compose.local PostgreSQL 宿主机测试端口")
expect_contains(compose_local_text, "env_file:", "docker-compose.local 使用 env_file")
expect_contains(compose_local_text, "- .env.test", "docker-compose.local 读取 .env.test")
expect_not_contains(compose_local_text, "APP_ADMIN_USERNAME: \\$\\{APP_ADMIN_USERNAME:-\\}", "docker-compose.local 不再依赖宿主机 APP_ADMIN_USERNAME 插值")
expect_not_contains(compose_local_text, "POSTGRES_PASSWORD: \\$\\{DB_PASSWORD:-ChangeMe123!\\}", "docker-compose.local 不再依赖宿主机 DB_PASSWORD 插值")
expect_contains(deployment_text, "轻量测试基础设施栈", "DEPLOYMENT_GUIDE compose1 定位")
expect_contains(compose_temp_text, "name: autotfl-test-infra", "docker-compose1 compose 名称")
expect_contains(compose_temp_text, "container_name: autotfl-test-infra-postgres", "docker-compose1 PostgreSQL 容器名")
expect_contains(compose_temp_text, "container_name: autotfl-test-infra-redis", "docker-compose1 Redis 容器名")
expect_contains(compose_temp_text, "5432:5432", "docker-compose1 PostgreSQL 宿主机测试端口")
expect_contains(compose_temp_text, "6379:6379", "docker-compose1 Redis 宿主机测试端口")
expect_contains(compose_server_text, "APP_ADMIN_USERNAME", "docker-compose.server 管理员用户名变量")
expect_contains(compose_server_text, "APP_ADMIN_EMAIL", "docker-compose.server 管理员邮箱变量")
expect_contains(compose_server_text, "APP_ADMIN_PASSWORD", "docker-compose.server 管理员密码变量")
expect_contains(env_example_text, "APP_ADMIN_USERNAME=admin", ".env.example 管理员用户名示例")
expect_contains(env_example_text, "APP_ADMIN_EMAIL=admin@example.com", ".env.example 管理员邮箱示例")
expect_contains(env_example_text, "APP_ADMIN_PASSWORD=__CHANGE_ME_ADMIN_PASSWORD__", ".env.example 管理员密码示例")
expect_contains(test_env_example_text, "APP_ADMIN_USERNAME=admin", ".env.test.example 管理员用户名")
expect_contains(test_env_example_text, "APP_ADMIN_EMAIL=admin@example.com", ".env.test.example 管理员邮箱")
expect_contains(test_env_example_text, "APP_ADMIN_PASSWORD=admin123", ".env.test.example 管理员密码")
expect_contains(test_env_example_text, "POSTGRES_PORT=5432", ".env.test.example 测试端口")
expect_not_contains(readme_text, "首个注册用户会自动成为系统管理员", "README 已移除自动管理员")
expect_not_contains(guide_text, "首个注册用户会自动成为系统管理员", "PROJECT_GUIDE 已移除自动管理员")
expect_not_contains(guide_text, "系统管理员可访问全部 workspace", "PROJECT_GUIDE 已移除管理员全局 workspace 访问口径")
expect_not_contains(spec_text, "全局管理权限", "PROJECT_SPEC 已移除全局管理权限口径")
expect_not_contains(deployment_text, "管理员可访问全部 workspace", "DEPLOYMENT_GUIDE 已移除管理员全局 workspace 访问口径")
expect_not_contains(deployment_text, "首个注册用户自动成为管理员", "DEPLOYMENT_GUIDE 已移除自动管理员")
expect_not_contains(readme_text, "暂不负责数据结果正确", "README 已移除结果正确性免责声明")
expect_not_contains(guide_text, "暂不负责数据结果正确", "PROJECT_GUIDE 已移除结果正确性免责声明")
expect_not_contains(deployment_text, "暂不负责数据结果正确", "DEPLOYMENT_GUIDE 已移除结果正确性免责声明")

cat("Access boundary guard passed.\n")
