library(testthat)

args <- commandArgs(trailingOnly = FALSE)
file_arg <- "--file="
script_path <- sub(file_arg, "", args[grep(file_arg, args)])
script_path <- if (length(script_path) > 0) script_path[[1]] else ""
script_dir <- dirname(normalizePath(script_path, winslash = "/", mustWork = FALSE))
project_root <- if (length(script_path) > 0 && nzchar(script_path)) {
  normalizePath(file.path(script_dir, ".."), winslash = "/", mustWork = TRUE)
} else {
  wd <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
  if (basename(wd) == "tests") normalizePath(file.path(wd, ".."), winslash = "/", mustWork = TRUE) else wd
}

graphics_module_path <- file.path(project_root, "modules", "statistical_graphics.R")
task_history_module_path <- file.path(project_root, "modules", "task_history.R")
common_ui_shell_path <- file.path(project_root, "modules", "statistical_graphics_ui", "common_ui_shell.R")
auth_path <- file.path(project_root, "modules", "common", "auth.R")
sql_path <- file.path(project_root, "postgres", "init.sql")

graphics_text <- paste(readLines(graphics_module_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
task_history_text <- paste(readLines(task_history_module_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
common_ui_text <- paste(readLines(common_ui_shell_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
auth_text <- paste(readLines(auth_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
sql_text <- paste(readLines(sql_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

test_that("统计图形总路由接入任务历史保存与加载入口", {
  expect_match(graphics_text, "任务历史")
  expect_match(graphics_text, "source\\(\"modules/task_history\\.R\"\\)")
  expect_match(graphics_text, "task_history_ui\\(")
  expect_match(graphics_text, "task_history_server\\(")
  expect_match(graphics_text, "module_handler_apply_state")
  expect_false(grepl("showNotification\\(paste0\\(\"保存预设失败: \", conditionMessage\\(e\\)\\)", graphics_text))
})

test_that("共享 task_history 模块承载任务历史 UI 与保存逻辑", {
  expect_match(task_history_text, "task_history_ui <- function")
  expect_match(task_history_text, "task_history_server <- function")
  expect_match(task_history_text, "service_save_analysis_state\\(")
  expect_match(task_history_text, "service_get_analysis_state\\(")
  expect_match(task_history_text, "service_delete_analysis_state\\(")
  expect_match(task_history_text, "task_history_operation_user_message")
  expect_match(task_history_text, "task_note")
  expect_match(task_history_text, "delete_task")
  expect_match(task_history_text, "图形参数未选择时系统会按空值/默认值保存，不应因此失败")
})

test_that("图形子模块统一使用完整快照保存，并保留复杂字段回填逻辑", {
  module_paths <- c(
    file.path(project_root, "modules", "statistical_graphics", "survival_analysis.R"),
    file.path(project_root, "modules", "statistical_graphics", "forest_plot.R"),
    file.path(project_root, "modules", "statistical_graphics", "spider_plot.R"),
    file.path(project_root, "modules", "statistical_graphics", "swimmer_plot.R"),
    file.path(project_root, "modules", "statistical_graphics", "boxplot.R"),
    file.path(project_root, "modules", "statistical_graphics", "heatmap.R"),
    file.path(project_root, "modules", "statistical_graphics", "correlation_matrix.R"),
    file.path(project_root, "modules", "statistical_graphics", "combo_plot.R"),
    file.path(project_root, "modules", "statistical_graphics", "waterfall_plot.R")
  )
  for (module_path in module_paths) {
    module_text <- paste(readLines(module_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
    expect_match(module_text, "graphics_build_task_state\\(", info = basename(module_path))
  }

  survival_text <- paste(readLines(module_paths[[1]], warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  spider_text <- paste(readLines(module_paths[[3]], warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  swimmer_text <- paste(readLines(module_paths[[4]], warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(survival_text, "graphics_restore_task_input_state\\(")
  expect_match(survival_text, "facet_value")
  expect_match(spider_text, "graphics_restore_task_input_state\\(")
  expect_match(swimmer_text, "event_ui_state\\(extra_state\\$event_mappings\\)")
  expect_match(swimmer_text, "start_time = graphics_state\\$start_time %\\|\\|% input\\$start_time")
  expect_match(swimmer_text, "end_time = graphics_state\\$end_time %\\|\\|% input\\$end_time")
  expect_match(swimmer_text, "lane_color_by = graphics_state\\$lane_color_by %\\|\\|% input\\$lane_color_by")
  expect_match(swimmer_text, "ongoing_var = graphics_state\\$ongoing_var %\\|\\|% input\\$ongoing_var")
  expect_match(swimmer_text, "graphics_state\\$lane_color_by <- extra_state\\$lane_color_by")
  expect_match(swimmer_text, "graphics_state\\$ongoing_var <- extra_state\\$ongoing_var")
  expect_match(swimmer_text, "restore_swimmer_mapping_inputs <- function")
  expect_match(swimmer_text, "restore_swimmer_mapping_inputs\\(force = TRUE, df_current = df_restore, state_snapshot = restore_snapshot\\)")
  expect_match(swimmer_text, "selected_start <- if \\(isTRUE\\(force\\)\\) state_start else isolate\\(input\\$start_time\\)")
  expect_match(swimmer_text, "selected_end <- if \\(isTRUE\\(force\\)\\) state_end else isolate\\(input\\$end_time\\)")
  expect_match(swimmer_text, "snapshot_get <- function\\(name, fallback = NULL\\)")
  expect_match(swimmer_text, "state_subject <- if \\(isTRUE\\(force\\)\\) snapshot_get\\(\"subject_id\", NULL\\)")
  expect_match(swimmer_text, "state_start <- if \\(isTRUE\\(force\\)\\) snapshot_get\\(\"start_time\", NULL\\)")
  expect_match(swimmer_text, "state_end <- if \\(isTRUE\\(force\\)\\) snapshot_get\\(\"end_time\", NULL\\)")
  expect_match(swimmer_text, "committed_params <- reactiveVal\\(NULL\\)")
  expect_match(swimmer_text, "build_swimmer_committed_params <- function")
  expect_match(swimmer_text, "committed_params\\(params\\)")
  expect_match(swimmer_text, "committed_params\\(NULL\\)")
  expect_match(swimmer_text, "linewidth = params\\$lane_size")
  expect_match(swimmer_text, "theme_minimal\\(base_size = params\\$base_font_size")
  expect_match(swimmer_text, "position = params\\$main_legend_position %\\|\\|% \"right\"")
  expect_match(swimmer_text, "graphics_compose_caption\\(params\\$plot_caption %\\|\\|% \"\", auto_caption_lines\\)")
  expect_match(swimmer_text, "format_missing_vec\\(\\.track_value, params = params\\)")
  expect_match(swimmer_text, "show_legend = isTRUE\\(params\\$show_legend\\)")
  expect_match(swimmer_text, "all_vars = all_vars_restore")
  expect_match(swimmer_text, "time_vars = time_vars_restore")
  expect_match(swimmer_text, "if \\(!isTRUE\\(force\\)\\) \\{\\s*snapshot_event_ui_state\\(\\)")
  expect_match(swimmer_text, "mapping_state_override = if \\(isTRUE\\(force\\)\\) state_snapshot\\$event_mappings %\\|\\|% list\\(\\) else NULL")
  expect_match(swimmer_text, "row_count_override = if \\(isTRUE\\(force\\)\\) length\\(state_snapshot\\$event_mappings %\\|\\|% list\\(\\)\\) else NULL")
  expect_match(swimmer_text, "prefer_state = isTRUE\\(force\\)")
  expect_match(swimmer_text, "SwimmerApplyStateEventFlushError")
  expect_match(swimmer_text, "SwimmerApplyStateError")
  expect_match(swimmer_text, "SwimmerApplyStateFlushError")
})

test_that("第一批图形参数抽象类沉淀到 common_ui_shell 并被代表性模块复用", {
  expect_match(common_ui_text, "graphics_column_mapping_panel_ui <- function")
  expect_match(common_ui_text, "graphics_time_axis_panel_ui <- function")
  expect_match(common_ui_text, "graphics_export_panel_ui <- function")
  expect_match(common_ui_text, "graphics_display_legend_panel_ui <- function")
  expect_match(common_ui_text, "graphics_text_label_panel_ui <- function")
  expect_match(common_ui_text, "graphics_symbol_style_panel_ui <- function")
  expect_match(common_ui_text, "graphics_point_shape_choices <- function")
  expect_match(common_ui_text, "graphics_palette_layout_panel_ui <- function")
  expect_match(common_ui_text, "graphics_palette_choice_values <- function")
  expect_match(common_ui_text, "graphics_axis_proportion_panel_ui <- function")
  expect_match(common_ui_text, "graphics_reference_threshold_panel_ui <- function")
  expect_match(common_ui_text, "graphics_group_style_mode_choices <- function")
  expect_match(common_ui_text, "graphics_group_style_mapping_panel_ui <- function")
  expect_match(common_ui_text, "graphics_group_style_rule_ui <- function")

  spider_path <- file.path(project_root, "modules", "statistical_graphics", "spider_plot.R")
  swimmer_path <- file.path(project_root, "modules", "statistical_graphics", "swimmer_plot.R")
  heatmap_path <- file.path(project_root, "modules", "statistical_graphics", "heatmap.R")
  corr_path <- file.path(project_root, "modules", "statistical_graphics", "correlation_matrix.R")
  waterfall_path <- file.path(project_root, "modules", "statistical_graphics", "waterfall_plot.R")
  survival_path <- file.path(project_root, "modules", "statistical_graphics", "survival_analysis.R")
  spider_text <- paste(readLines(spider_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  swimmer_text <- paste(readLines(swimmer_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  heatmap_text <- paste(readLines(heatmap_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  corr_text <- paste(readLines(corr_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  waterfall_text <- paste(readLines(waterfall_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  survival_text <- paste(readLines(survival_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

  expect_match(spider_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(spider_text, "graphics_time_axis_panel_ui\\(")
  expect_match(spider_text, "graphics_export_panel_ui\\(")
  expect_match(spider_text, "graphics_display_legend_panel_ui\\(")
  expect_match(spider_text, "graphics_text_label_panel_ui\\(")
  expect_match(spider_text, "graphics_palette_layout_panel_ui\\(")
  expect_match(spider_text, "graphics_axis_proportion_panel_ui\\(")
  expect_match(spider_text, "graphics_reference_threshold_panel_ui\\(")
  expect_match(swimmer_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(swimmer_text, "graphics_time_axis_panel_ui\\(")
  expect_match(swimmer_text, "graphics_export_panel_ui\\(")
  expect_match(swimmer_text, "title = \"显示与图例\"")
  expect_match(swimmer_text, "graphics_display_legend_panel_ui\\(")
  expect_match(swimmer_text, "graphics_symbol_style_panel_ui\\(")
  expect_match(swimmer_text, "graphics_palette_layout_panel_ui\\(")
  expect_match(swimmer_text, "graphics_axis_proportion_panel_ui\\(")
  expect_match(swimmer_text, "graphics_group_style_rule_ui\\(")
  expect_match(swimmer_text, "graphics_group_style_mapping_panel_ui\\(")
  expect_match(swimmer_text, "graphics_card_panel_ui\\(\\s*\"轨道与排序\"")
  expect_match(swimmer_text, "graphics_group_style_mapping_panel_ui\\(\\s*\"事件分组样式\"")
  expect_match(swimmer_text, "graphics_group_style_mapping_panel_ui\\(\\s*\"分组颜色映射\"")
  expect_match(swimmer_text, "graphics_text_label_panel_ui\\(")
  expect_match(heatmap_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(heatmap_text, "graphics_export_panel_ui\\(")
  expect_match(corr_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(corr_text, "graphics_export_panel_ui\\(")
  expect_match(waterfall_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(waterfall_text, "graphics_display_legend_panel_ui\\(")
  expect_match(waterfall_text, "graphics_symbol_style_panel_ui\\(")
  expect_match(waterfall_text, "graphics_palette_layout_panel_ui\\(")
  expect_match(waterfall_text, "graphics_axis_proportion_panel_ui\\(")
  expect_match(waterfall_text, "graphics_group_style_mapping_panel_ui\\(")
  expect_match(waterfall_text, "graphics_reference_threshold_panel_ui\\(")
  expect_match(waterfall_text, "graphics_card_panel_ui\\(\\s*\"排序和显示\"")
  expect_match(waterfall_text, "graphics_card_panel_ui\\(\\s*\"轨道与缺失值\"")
  expect_match(waterfall_text, "graphics_text_label_panel_ui\\(")
  expect_match(survival_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(survival_text, "graphics_text_label_panel_ui\\(")
  expect_match(survival_text, "graphics_card_panel_ui\\(\\s*\"曲线、删失点与风险表\"")
  expect_match(survival_text, "graphics_card_panel_ui\\(\\s*\"统计标注与位置\"")
  expect_match(survival_text, "graphics_card_panel_ui\\(\\s*\"图形与图例文字\"")
  expect_match(survival_text, "graphics_card_panel_ui\\(\\s*\"风险表文字\"")
  expect_match(survival_text, "中位生存辅助线")
  expect_match(survival_text, "显示中位生存时间文本标注")
  expect_match(survival_text, "显示统计摘要（Log-rank P；分层时附加 HR）")
  expect_match(survival_text, "仅在未分层时生效；统一用于主图图例、风险表、数据表与统计报告")
  expect_match(survival_text, "统计摘要中的 HR 以")
  expect_match(survival_text, "交互式生存曲线")
  expect_no_match(survival_text, "else if \\(!is.null\\(input\\$time_range\\)")
})

test_that("第二批抽象第一版提供动态映射行容器并接入泳道图事件映射", {
  expect_match(common_ui_text, "graphics_dynamic_mapping_rows_panel_ui <- function")
  expect_match(common_ui_text, "graphics_dynamic_mapping_fields_ui <- function")
  expect_match(common_ui_text, "graphics_build_overlay_point_layer_fields_spec <- function")
  expect_match(common_ui_text, "graphics_build_event_mapping_fields_spec <- function")
  swimmer_path <- file.path(project_root, "modules", "statistical_graphics", "swimmer_plot.R")
  swimmer_text <- paste(readLines(swimmer_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(swimmer_text, "graphics_dynamic_mapping_rows_panel_ui\\(")
  expect_match(swimmer_text, "graphics_dynamic_mapping_fields_ui\\(session\\$ns, event_row_fields\\)")
  expect_match(swimmer_text, "graphics_build_overlay_point_layer_fields_spec\\(")
  expect_match(swimmer_text, "title = \"事件映射\"")
  expect_match(swimmer_text, "add_button_id = \"add_event_map\"")
  expect_match(swimmer_text, "remove_button_id = \"remove_event_map\"")
  expect_match(swimmer_text, "轨道默认展示方式")
  expect_match(swimmer_text, "这里设置的是新选轨道的默认展示方式")
  expect_match(swimmer_text, "泳道终点-降序")
  expect_match(swimmer_text, "泳道终点-升序")
  expect_match(swimmer_text, "这里的“泳道终点”指换算后的随访终点位置")
  expect_match(swimmer_text, "事件总图例标题")
  expect_match(swimmer_text, "这里控制事件图例整体层级")
  expect_match(swimmer_text, "轨道总图例标题")
  expect_match(swimmer_text, "这里控制下方分组轨道区的显示方式与总图例标题")
  expect_match(swimmer_text, "下方轨道区占比")
  expect_match(swimmer_text, "“空值显示方式”影响轨道和数据表中的缺失文本")
  expect_match(swimmer_text, "“下方轨道区占比”和“全局字号”影响主图与下方轨道区的版式比例")
})

test_that("泳道图任务历史显式保存并恢复动态样式状态", {
  swimmer_path <- file.path(project_root, "modules", "statistical_graphics", "swimmer_plot.R")
  swimmer_text <- paste(readLines(swimmer_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(swimmer_text, "capture_lane_manual_color_values <- function")
  expect_match(swimmer_text, "capture_track_mode_map <- function")
  expect_match(swimmer_text, "capture_track_color_values <- function")
  expect_match(swimmer_text, "capture_event_style_snapshot <- function")
  expect_match(swimmer_text, "restore_swimmer_dynamic_style_inputs <- function")
  expect_match(swimmer_text, "track_mode_map = track_mode_map")
  expect_match(swimmer_text, "lane_manual_colors = capture_lane_manual_color_values")
  expect_match(swimmer_text, "track_color_values = capture_track_color_values")
  expect_match(swimmer_text, "capture_event_style_snapshot\\(i, df_state\\)")
  expect_match(swimmer_text, "collect_swimmer_event_mappings <- function")
  expect_match(swimmer_text, "event_mappings = collect_swimmer_event_mappings\\(df_state\\)")
  expect_match(swimmer_text, "SwimmerApplyStateDynamicStyleError")
})

test_that("analysis_states 同时写入运行时建表与初始化 SQL", {
  expect_match(auth_text, "CREATE TABLE IF NOT EXISTS analysis_states")
  expect_match(sql_text, "CREATE TABLE IF NOT EXISTS analysis_states")
  expect_match(auth_text, "state_note TEXT")
  expect_match(sql_text, "state_note TEXT")
  expect_match(auth_text, "idx_analysis_states_user_scope")
  expect_match(sql_text, "idx_analysis_states_user_scope")
})

test_that("生存图删失点样式开始复用共享点形状枚举", {
  survival_path <- file.path(project_root, "modules", "statistical_graphics", "survival_analysis.R")
  survival_text <- paste(readLines(survival_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(survival_text, "graphics_point_shape_choices\\(\\)")
  expect_match(survival_text, "strata_labels = graphics_state\\$strata_labels %\\|\\|% list\\(\\)")
  expect_match(survival_text, "if \\(is.list\\(extra_state\\$strata_labels\\)\\) graphics_state\\$strata_labels <- extra_state\\$strata_labels")
  expect_match(survival_text, "\\.survival_strata_label_input_id\\(label_name\\)")
  expect_match(survival_text, "km_show_censor = input\\$km_show_censor")
  expect_match(survival_text, "plot_title = input\\$plot_title")
  expect_match(survival_text, "plot_caption = input\\$plot_caption")
  expect_match(survival_text, "if \\(isTRUE\\(params\\$km_show_censor\\)\\)")
  expect_match(survival_text, "output\\$survival_report <- renderUI\\(")
  expect_match(survival_text, "params <- committed_params\\(\\)")
  expect_match(survival_text, "if \\(isTRUE\\(params\\$show_median\\) && !is.null\\(med\\)")
  expect_match(survival_text, "hr_lines <- if \\(isTRUE\\(params\\$show_stats\\)\\)")
  expect_match(survival_text, "summary_items <- c\\(median_lines, hr_lines\\)")
  expect_no_match(survival_text, "tags\\$div\\(\\s*class = \"panel panel-default\",\\s*tags\\$div\\(class = \"panel-heading\", \"图例与文字\"")
})

test_that("阶段性收口清单与代表模块 raw panel 基线被锁定", {
  guide_path <- file.path(project_root, "PROJECT_GUIDE.md")
  guide_text <- paste(readLines(guide_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(guide_text, "阶段性收口清单（代表模块）")
  expect_match(guide_text, "`spider_plot\\.R`：普通设置型面板已全部切换到 common；剩余 raw panel `0`。")
  expect_match(guide_text, "`waterfall_plot\\.R`：普通设置型面板已全部切换到 common；剩余 raw panel `0`。")
  expect_match(guide_text, "`swimmer_plot\\.R`：普通设置型面板已全部切换到 common；剩余 raw panel `0`。")
  expect_match(guide_text, "`swimmer_plot\\.R` 第三轮：将主图、事件层、下方轨道区、自绘事件图例、底部脚注与静态图高度统一改为只读取点击“生成图形”时捕获的 committed 参数快照")
  expect_match(guide_text, "`swimmer_plot\\.R` 第四轮：继续收紧已确定的语义文案")
  expect_match(guide_text, "当前表示按汇总后的“泳道终点”排序")
  expect_match(guide_text, "下一轮优先级")

  spider_path <- file.path(project_root, "modules", "statistical_graphics", "spider_plot.R")
  swimmer_path <- file.path(project_root, "modules", "statistical_graphics", "swimmer_plot.R")
  waterfall_path <- file.path(project_root, "modules", "statistical_graphics", "waterfall_plot.R")
  spider_text <- paste(readLines(spider_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  swimmer_text <- paste(readLines(swimmer_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  waterfall_text <- paste(readLines(waterfall_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

  expect_equal(length(gregexpr("panel panel-default", spider_text, fixed = TRUE)[[1]][gregexpr("panel panel-default", spider_text, fixed = TRUE)[[1]] > 0]), 0)
  expect_equal(length(gregexpr("panel panel-default", waterfall_text, fixed = TRUE)[[1]][gregexpr("panel panel-default", waterfall_text, fixed = TRUE)[[1]] > 0]), 0)
  expect_equal(length(gregexpr("panel panel-default", swimmer_text, fixed = TRUE)[[1]][gregexpr("panel panel-default", swimmer_text, fixed = TRUE)[[1]] > 0]), 0)
  expect_match(swimmer_text, "graphics_dynamic_mapping_row_ui\\(")
  expect_match(swimmer_text, "paste0\\(\"事件变量组 \", i\\)")
})

test_that("analysis_states service 对个人任务使用 NULL workspace SQL 分支", {
  account_service_path <- file.path(project_root, "modules", "common", "account_service.R")
  account_text <- paste(readLines(account_service_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(account_text, "service_build_analysis_state_insert_spec")
  expect_match(account_text, "VALUES \\(\\$1, \\$2, NULL, \\$3, \\$4, \\$5, \\$6, \\$7, NOW\\(\\), NOW\\(\\)\\)")
  expect_match(account_text, "service_delete_analysis_state")
  expect_match(account_text, "match_workspace = TRUE")
})
