test_find_project_root <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- "--file="
  script_path <- sub(file_arg, "", args[grep(file_arg, args)])
  script_path <- if (length(script_path) > 0) script_path[[1]] else ""
  start_candidates <- unique(c(
    if (nzchar(script_path)) dirname(normalizePath(script_path, winslash = "/", mustWork = FALSE)) else character(0),
    normalizePath(getwd(), winslash = "/", mustWork = FALSE)
  ))

  for (candidate in start_candidates) {
    current <- candidate
    repeat {
      if (file.exists(file.path(current, "app.R")) &&
          dir.exists(file.path(current, "modules")) &&
          dir.exists(file.path(current, "tests"))) {
        return(normalizePath(current, winslash = "/", mustWork = TRUE))
      }
      parent <- dirname(current)
      if (identical(parent, current)) break
      current <- parent
    }
  }

  stop("无法定位项目根目录。", call. = FALSE)
}

project_root <- test_find_project_root()
setwd(file.path(project_root, "tests"))
library(testthat)

args <- commandArgs(trailingOnly = FALSE)
file_arg <- "--file="
script_path <- sub(file_arg, "", args[grep(file_arg, args)])
script_path <- if (length(script_path) > 0) script_path[[1]] else ""
script_dir <- dirname(normalizePath(script_path, winslash = "/", mustWork = FALSE))
project_root <- test_find_project_root()

graphics_module_path <- file.path(project_root, "modules", "statistical_graphics.R")
task_history_module_path <- file.path(project_root, "modules", "task_history.R")
common_ui_shell_path <- file.path(project_root, "modules", "statistical_graphics_ui", "common_ui_shell.R")
forest_table_state_helper_path <- file.path(project_root, "modules", "common", "graphics", "forest_table_state_helpers.R")
forest_result_helper_path <- file.path(project_root, "modules", "common", "graphics", "forest_result_schema_helpers.R")
forest_model_helper_path <- file.path(project_root, "modules", "common", "graphics", "forest_model_helpers.R")
forest_pipeline_helper_path <- file.path(project_root, "modules", "common", "graphics", "forest_analysis_pipeline.R")
auth_path <- file.path(project_root, "modules", "common", "auth", "auth.R")
sql_path <- file.path(project_root, "postgres", "init.sql")

graphics_text <- paste(readLines(graphics_module_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
task_history_text <- paste(readLines(task_history_module_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
common_ui_text <- paste(readLines(common_ui_shell_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
forest_table_state_text <- paste(readLines(forest_table_state_helper_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
forest_result_helper_text <- paste(readLines(forest_result_helper_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
forest_model_helper_text <- paste(readLines(forest_model_helper_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
forest_pipeline_helper_text <- paste(readLines(forest_pipeline_helper_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
auth_text <- paste(readLines(auth_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
sql_text <- paste(readLines(sql_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

test_that("统计图形总路由接入任务历史保存与加载入口", {
  expect_match(graphics_text, "任务历史")
  expect_match(graphics_text, "source\\(\"modules/task_history\\.R\"\\)")
  expect_match(graphics_text, "source\\(\"modules/common/graphics/forest_table_state_helpers\\.R\"\\)")
  expect_match(graphics_text, "source\\(\"modules/common/graphics/forest_result_schema_helpers\\.R\"\\)")
  expect_match(graphics_text, "source\\(\"modules/common/graphics/forest_model_helpers\\.R\"\\)")
  expect_match(graphics_text, "source\\(\"modules/common/graphics/forest_analysis_pipeline\\.R\"\\)")
  expect_match(graphics_text, "task_history_ui\\(")
  expect_match(graphics_text, "task_history_server\\(")
  expect_match(graphics_text, "module_handler_apply_state")
  expect_false(grepl("showNotification\\(paste0\\(\"保存预设失败: \", conditionMessage\\(e\\)\\)", graphics_text))
})

test_that("共享 task_history 模块承载任务历史 UI 与保存逻辑", {
  expect_match(task_history_text, "task_history_ui <- function")
  expect_match(task_history_text, "task_history_server <- function")
  expect_match(task_history_text, "service_save_analysis_state\\(")
  expect_match(task_history_text, "service_get_analysis_state\\(")
  expect_match(task_history_text, "service_delete_analysis_state\\(")
  expect_match(task_history_text, "task_history_operation_user_message")
  expect_match(task_history_text, "task_note")
  expect_match(task_history_text, "delete_task")
  expect_match(task_history_text, "图形参数未选择时系统会按空值/默认值保存，不应因此失败")
})

test_that("图形子模块统一使用完整快照保存，并保留复杂字段回填逻辑", {
  module_paths <- c(
    file.path(project_root, "modules", "statistical_graphics", "survival_analysis.R"),
    file.path(project_root, "modules", "statistical_graphics", "forest_plot.R"),
    file.path(project_root, "modules", "statistical_graphics", "spider_plot.R"),
    file.path(project_root, "modules", "statistical_graphics", "swimmer_plot.R"),
    file.path(project_root, "modules", "statistical_graphics", "boxplot.R"),
    file.path(project_root, "modules", "statistical_graphics", "heatmap.R"),
    file.path(project_root, "modules", "statistical_graphics", "correlation_matrix.R"),
    file.path(project_root, "modules", "statistical_graphics", "combo_plot.R"),
    file.path(project_root, "modules", "statistical_graphics", "waterfall_plot.R")
  )
  for (module_path in module_paths) {
    module_text <- paste(readLines(module_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
    expect_match(module_text, "graphics_build_task_state\\(", info = basename(module_path))
  }

  forest_text <- paste(readLines(module_paths[[2]], warn = FALSE, encoding = "UTF-8"), collapse = "\n")

  survival_text <- paste(readLines(module_paths[[1]], warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  spider_text <- paste(readLines(module_paths[[3]], warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  swimmer_text <- paste(readLines(module_paths[[4]], warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  combo_text <- paste(readLines(module_paths[[8]], warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(survival_text, "graphics_restore_task_input_state\\(")
  expect_match(forest_text, "graphics_restore_task_input_state\\(")
  expect_match(forest_text, "exclude_ids = c\\(\"generate\", \"run_analysis\", \"selected_table_cols\"\\)")
  expect_match(forest_text, "selected_table_cols = column_state\\$selected_cols")
  expect_match(forest_text, "display_names = column_state\\$display_names")
  expect_match(forest_text, "alignments = column_state\\$alignments")
  expect_match(forest_text, "apply_state = apply_state")
  expect_match(forest_text, "graphics_output_action_bar_ui\\(")
  expect_match(forest_text, "session\\$sendInputMessage|graphics_restore_task_input_state\\(")
  expect_match(forest_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(forest_text, "graphics_table_panel_ui\\(")
  expect_match(forest_text, "graphics_text_label_panel_ui\\(")
  expect_match(forest_text, "graphics_axis_proportion_panel_ui\\(")
  expect_match(forest_text, "graphics_axis_range_controls_ui\\(")
  expect_match(forest_text, "graphics_axis_tick_format_controls_ui\\(")
  expect_match(forest_text, "graphics_palette_layout_panel_ui\\(")
  expect_match(forest_text, "graphics_export_panel_ui\\(")
  expect_match(forest_text, "forest_result_data <- reactive\\(")
  expect_match(forest_text, "forest_task_state_exclude_patterns <- c\\(")
  expect_match(forest_text, "\"\\^name_\"")
  expect_match(forest_text, "\"\\^align_\"")
  expect_match(forest_text, "forest_persist_selected_column_inputs\\(")
  expect_match(forest_text, "forest_collect_selected_column_state\\(")
  expect_match(forest_text, "forest_restore_selected_column_state\\(")
  expect_match(forest_text, "current_selected <- forest_normalize_selected_columns\\(")
  expect_match(forest_text, "selected_cols <- forest_normalize_selected_columns\\(input\\$selected_table_cols\\)")
  expect_match(forest_text, "graphics_reference_threshold_panel_ui\\(")
  expect_match(forest_text, "graphics_reference_line_ui\\(")
  expect_match(forest_text, "graphics_collect_reference_line_spec\\(")
  expect_match(forest_text, "graphics_add_reference_lines\\(")
  expect_match(forest_table_state_text, "forest_default_column_alignment <- function")
  expect_match(forest_table_state_text, "forest_normalize_selected_columns <- function")
  expect_match(forest_table_state_text, "forest_persist_selected_column_inputs <- function")
  expect_match(forest_table_state_text, "forest_collect_selected_column_state <- function")
  expect_match(forest_table_state_text, "forest_restore_selected_column_state <- function")
  expect_match(forest_result_helper_text, "forest_normalize_result_schema <- function")
  expect_match(forest_result_helper_text, "forest_extract_model_result <- function")
  expect_match(forest_result_helper_text, "forest_finalize_analysis_results <- function")
  expect_match(forest_result_helper_text, "forest_subgroup <- as\\.character")
  expect_match(forest_result_helper_text, "forest_estimate <-")
  expect_match(forest_model_helper_text, "forest_prepare_analysis_dataframe <- function")
  expect_match(forest_model_helper_text, "forest_build_model_formula <- function")
  expect_match(forest_model_helper_text, "forest_fit_analysis_model <- function")
  expect_match(forest_pipeline_helper_text, "forest_run_analysis_pipeline <- function")
  expect_match(survival_text, "facet_value")
  expect_match(spider_text, "graphics_restore_task_input_state\\(")
  expect_match(swimmer_text, "event_ui_state\\(extra_state\\$event_mappings\\)")
  expect_match(swimmer_text, "start_time = graphics_state\\$start_time %\\|\\|% input\\$start_time")
  expect_match(swimmer_text, "end_time = graphics_state\\$end_time %\\|\\|% input\\$end_time")
  expect_match(swimmer_text, "lane_color_by = graphics_state\\$lane_color_by %\\|\\|% input\\$lane_color_by")
  expect_match(swimmer_text, "ongoing_var = graphics_state\\$ongoing_var %\\|\\|% input\\$ongoing_var")
  expect_match(swimmer_text, "graphics_state\\$lane_color_by <- extra_state\\$lane_color_by")
  expect_match(swimmer_text, "graphics_state\\$ongoing_var <- extra_state\\$ongoing_var")
  expect_match(swimmer_text, "restore_swimmer_mapping_inputs <- function")
  expect_match(swimmer_text, "restore_swimmer_mapping_inputs\\(force = TRUE, df_current = df_restore, state_snapshot = restore_snapshot\\)")
  expect_match(swimmer_text, "selected_start <- if \\(isTRUE\\(force\\)\\) state_start else isolate\\(input\\$start_time\\)")
  expect_match(swimmer_text, "selected_end <- if \\(isTRUE\\(force\\)\\) state_end else isolate\\(input\\$end_time\\)")
  expect_match(swimmer_text, "snapshot_get <- function\\(name, fallback = NULL\\)")
  expect_match(swimmer_text, "state_subject <- if \\(isTRUE\\(force\\)\\) snapshot_get\\(\"subject_id\", NULL\\)")
  expect_match(swimmer_text, "state_start <- if \\(isTRUE\\(force\\)\\) snapshot_get\\(\"start_time\", NULL\\)")
  expect_match(swimmer_text, "state_end <- if \\(isTRUE\\(force\\)\\) snapshot_get\\(\"end_time\", NULL\\)")
  expect_match(swimmer_text, "committed_params <- reactiveVal\\(NULL\\)")
  expect_match(swimmer_text, "restoring_event_controls <- reactiveVal\\(FALSE\\)")
  expect_match(swimmer_text, "build_swimmer_committed_params <- function")
  expect_match(swimmer_text, "committed_params\\(params\\)")
  expect_match(swimmer_text, "committed_params\\(NULL\\)")
  expect_match(swimmer_text, "linewidth = params\\$lane_size")
  expect_match(swimmer_text, "theme_minimal\\(base_size = params\\$base_font_size")
  expect_match(swimmer_text, "position = params\\$main_legend_position %\\|\\|% \"right\"")
  expect_match(swimmer_text, "graphics_compose_caption\\(params\\$plot_caption %\\|\\|% \"\", auto_caption_lines\\)")
  expect_match(swimmer_text, "format_missing_vec\\(\\.track_value, params = params\\)")
  expect_match(swimmer_text, "show_legend = isTRUE\\(params\\$show_legend\\)")
  expect_match(swimmer_text, "prefer_state <- isTRUE\\(restoring_event_controls\\(\\)\\)")
  expect_match(swimmer_text, "selected_time <- if \\(prefer_state\\)")
  expect_match(swimmer_text, "legend_title_raw <- if \\(prefer_state\\)")
  expect_match(swimmer_text, "event_type_var <- if \\(prefer_state\\)")
  expect_match(swimmer_text, "restoring_event_controls\\(TRUE\\)")
  expect_match(swimmer_text, "restoring_event_controls\\(FALSE\\)")
  expect_match(swimmer_text, "outputOptions\\(output, \"event_mapping_ui\", suspendWhenHidden = FALSE\\)")
  expect_match(swimmer_text, "outputOptions\\(output, \"event_group_style_controls\", suspendWhenHidden = FALSE\\)")
  expect_match(swimmer_text, "outputOptions\\(output, \"track_mode_controls\", suspendWhenHidden = FALSE\\)")
  expect_match(swimmer_text, "outputOptions\\(output, \"track_color_controls\", suspendWhenHidden = FALSE\\)")
  expect_match(swimmer_text, "all_vars = all_vars_restore")
  expect_match(swimmer_text, "time_vars = time_vars_restore")
  expect_match(swimmer_text, "if \\(!isTRUE\\(force\\)\\) \\{\\s*snapshot_event_ui_state\\(\\)")
  expect_match(swimmer_text, "mapping_state_override = if \\(isTRUE\\(force\\)\\) state_snapshot\\$event_mappings %\\|\\|% list\\(\\) else NULL")
  expect_match(swimmer_text, "row_count_override = if \\(isTRUE\\(force\\)\\) length\\(state_snapshot\\$event_mappings %\\|\\|% list\\(\\)\\) else NULL")
  expect_match(swimmer_text, "prefer_state = isTRUE\\(force\\)")
  expect_match(swimmer_text, "SwimmerApplyStateEventFlushError")
  expect_match(swimmer_text, "SwimmerApplyStateError")
  expect_match(swimmer_text, "SwimmerApplyStateFlushError")
  expect_no_match(swimmer_text, "suggested_tracks <- c\\(")
  expect_match(combo_text, "graphics_task_payload_input_state\\(")
  expect_match(combo_text, "graphics_task_payload_extra_state\\(")
  expect_match(combo_text, "base_ids <- c\\(")
  expect_match(combo_text, "\"plot_types\", \"combo_method\"")
  expect_match(combo_text, "session\\$onFlushed\\(function\\(\\)")
  expect_match(combo_text, "list\\(input_state = dynamic_state, extra_state = list\\(\\)\\)")
  expect_match(combo_text, "updateCheckboxGroupInput\\(session, \"plot_types\"")
  expect_match(combo_text, "updateRadioButtons\\(session, \"combo_method\"")
})

test_that("第一批图形参数抽象类沉淀到 common_ui_shell 并被代表性模块复用", {
  expect_match(common_ui_text, "graphics_column_mapping_panel_ui <- function")
  expect_match(common_ui_text, "graphics_time_axis_panel_ui <- function")
  expect_match(common_ui_text, "graphics_export_panel_ui <- function")
  expect_match(common_ui_text, "graphics_result_repro_tab_ui <- function")
  expect_match(common_ui_text, "graphics_bind_repro_code_output <- function")
  expect_match(common_ui_text, "graphics_display_legend_panel_ui <- function")
  expect_match(common_ui_text, "graphics_table_panel_ui <- function")
  expect_match(common_ui_text, "graphics_text_label_panel_ui <- function")
  expect_match(common_ui_text, "graphics_symbol_style_panel_ui <- function")
  expect_match(common_ui_text, "graphics_point_shape_choices <- function")
  expect_match(common_ui_text, "graphics_palette_layout_panel_ui <- function")
  expect_match(common_ui_text, "graphics_palette_choice_values <- function")
  expect_match(common_ui_text, "graphics_axis_proportion_panel_ui <- function")
  expect_match(common_ui_text, "graphics_reference_threshold_panel_ui <- function")
  expect_match(common_ui_text, "graphics_group_style_mode_choices <- function")
  expect_match(common_ui_text, "graphics_group_style_mapping_panel_ui <- function")
  expect_match(common_ui_text, "graphics_group_style_rule_ui <- function")

  spider_path <- file.path(project_root, "modules", "statistical_graphics", "spider_plot.R")
  swimmer_path <- file.path(project_root, "modules", "statistical_graphics", "swimmer_plot.R")
  boxplot_path <- file.path(project_root, "modules", "statistical_graphics", "boxplot.R")
  heatmap_path <- file.path(project_root, "modules", "statistical_graphics", "heatmap.R")
  corr_path <- file.path(project_root, "modules", "statistical_graphics", "correlation_matrix.R")
  combo_path <- file.path(project_root, "modules", "statistical_graphics", "combo_plot.R")
  forest_path <- file.path(project_root, "modules", "statistical_graphics", "forest_plot.R")
  waterfall_path <- file.path(project_root, "modules", "statistical_graphics", "waterfall_plot.R")
  survival_path <- file.path(project_root, "modules", "statistical_graphics", "survival_analysis.R")
  spider_text <- paste(readLines(spider_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  swimmer_text <- paste(readLines(swimmer_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  boxplot_text <- paste(readLines(boxplot_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  heatmap_text <- paste(readLines(heatmap_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  corr_text <- paste(readLines(corr_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  combo_text <- paste(readLines(combo_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  forest_text <- paste(readLines(forest_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  waterfall_text <- paste(readLines(waterfall_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  survival_text <- paste(readLines(survival_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

  expect_match(spider_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(spider_text, "graphics_time_axis_panel_ui\\(")
  expect_match(spider_text, "graphics_output_action_bar_ui\\(")
  expect_match(spider_text, "graphics_display_legend_panel_ui\\(")
  expect_match(spider_text, "graphics_text_label_panel_ui\\(")
  expect_match(spider_text, "graphics_palette_layout_panel_ui\\(")
  expect_match(spider_text, "graphics_axis_proportion_panel_ui\\(")
  expect_match(spider_text, "graphics_reference_threshold_panel_ui\\(")
  expect_match(spider_text, "\"数据与变量\"")
  expect_match(spider_text, "\"图形与样式\"")
  expect_match(spider_text, "\"输出与导出\"")
  expect_match(spider_text, "tabPanel\\(\\s*\"核心映射\"")
  expect_match(spider_text, "tabPanel\\(\\s*\"分组/分面/附加变量\"")
  expect_match(spider_text, "\"标题与说明\"")
  expect_match(spider_text, "title = \"标题与说明\"")
  expect_match(spider_text, "\"显示与坐标\"")
  expect_match(spider_text, "\"图层样式\"")
  expect_match(spider_text, "title = \"图层样式\"")
  expect_match(spider_text, "\"参考线与阈值\"")
  expect_match(spider_text, "\"尺寸与画布\"")
  expect_match(spider_text, "\"导出参数\"")
  expect_match(spider_text, "title = \"结果区\"")
  expect_match(spider_text, "tabPanel\\(\\s*\"交互图\"")
  expect_match(spider_text, "tabPanel\\(\\s*\"数据\"")
  expect_match(swimmer_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(swimmer_text, "graphics_time_axis_panel_ui\\(")
  expect_match(swimmer_text, "graphics_output_action_bar_ui\\(")
  expect_match(swimmer_text, "graphics_display_legend_panel_ui\\(")
  expect_match(swimmer_text, "graphics_symbol_style_panel_ui\\(")
  expect_match(swimmer_text, "graphics_palette_layout_panel_ui\\(")
  expect_match(swimmer_text, "graphics_axis_proportion_panel_ui\\(")
  expect_match(swimmer_text, "graphics_group_style_rule_ui\\(")
  expect_match(swimmer_text, "graphics_group_style_mapping_panel_ui\\(")
  expect_match(swimmer_text, "graphics_card_panel_ui\\(\\s*title = \"轨道变量与排序\"")
  expect_match(swimmer_text, "graphics_group_style_mapping_panel_ui\\(\\s*\"事件分组样式\"")
  expect_match(swimmer_text, "graphics_group_style_mapping_panel_ui\\(\\s*\"分组颜色映射\"")
  expect_match(swimmer_text, "graphics_text_label_panel_ui\\(")
  expect_match(swimmer_text, "\"数据与变量\"")
  expect_match(swimmer_text, "\"图形与样式\"")
  expect_match(swimmer_text, "\"输出与导出\"")
  expect_match(swimmer_text, "tabPanel\\(\\s*\"核心映射\"")
  expect_match(swimmer_text, "tabPanel\\(\\s*\"分组/分面/轨道/附加变量\"")
  expect_match(swimmer_text, "\"标题与说明\"")
  expect_match(swimmer_text, "\"显示与坐标\"")
  expect_match(swimmer_text, "\"图层样式\"")
  expect_match(swimmer_text, "\"参考线与阈值\"")
  expect_match(swimmer_text, "\"尺寸与画布\"")
  expect_match(swimmer_text, "\"导出参数\"")
  expect_match(swimmer_text, "title = \"结果区\"")
  expect_match(swimmer_text, "tabPanel\\(\\s*\"交互图\"")
  expect_match(swimmer_text, "tabPanel\\(\\s*\"数据\"")
  expect_match(swimmer_text, "tabPanel\\(\\s*\"泳道数据\"")
  expect_match(swimmer_text, "tabPanel\\(\\s*\"事件数据\"")
  expect_match(swimmer_text, "tabPanel\\(\\s*\"分组轨道数据\"")
  expect_match(boxplot_text, "\"数据与变量\"")
  expect_match(boxplot_text, "\"图形与样式\"")
  expect_match(boxplot_text, "\"输出与导出\"")
  expect_match(boxplot_text, "tabPanel\\(\\s*\"核心映射\"")
  expect_match(boxplot_text, "tabPanel\\(\\s*\"分组/分面/轨道/附加变量\"")
  expect_match(boxplot_text, "tabPanel\\(\\s*\"标题与说明\"")
  expect_match(boxplot_text, "tabPanel\\(\\s*\"显示与坐标\"")
  expect_match(boxplot_text, "tabPanel\\(\\s*\"图层样式\"")
  expect_match(boxplot_text, "tabPanel\\(\\s*\"参考线与阈值\"")
  expect_match(boxplot_text, "tabPanel\\(\\s*\"尺寸与画布\"")
  expect_match(boxplot_text, "tabPanel\\(\\s*\"导出参数\"")
  expect_match(boxplot_text, "graphics_output_action_bar_ui\\(")
  expect_match(boxplot_text, "title = \"结果区\"")
  expect_match(boxplot_text, "tabPanel\\(\\s*\"交互图\"")
  expect_match(boxplot_text, "tabPanel\\(\\s*\"数据\"")
  expect_match(heatmap_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(heatmap_text, "graphics_output_action_bar_ui\\(")
  expect_match(heatmap_text, "\"数据与变量\"")
  expect_match(heatmap_text, "\"图形与样式\"")
  expect_match(heatmap_text, "\"输出与导出\"")
  expect_match(heatmap_text, "tabPanel\\(\\s*\"核心映射\"")
  expect_match(heatmap_text, "tabPanel\\(\\s*\"分组/分面/轨道/附加变量\"")
  expect_match(heatmap_text, "tabPanel\\(\\s*\"标题与说明\"")
  expect_match(heatmap_text, "tabPanel\\(\\s*\"显示与坐标\"")
  expect_match(heatmap_text, "tabPanel\\(\\s*\"图层样式\"")
  expect_match(heatmap_text, "tabPanel\\(\\s*\"参考线与阈值\"")
  expect_match(heatmap_text, "tabPanel\\(\\s*\"尺寸与画布\"")
  expect_match(heatmap_text, "tabPanel\\(\\s*\"导出参数\"")
  expect_match(heatmap_text, "title = \"结果区\"")
  expect_match(heatmap_text, "tabPanel\\(\\s*\"交互图\"")
  expect_match(heatmap_text, "tabPanel\\(\\s*\"数据\"")
  expect_match(corr_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(corr_text, "graphics_output_action_bar_ui\\(")
  expect_match(corr_text, "\"数据与变量\"")
  expect_match(corr_text, "\"图形与样式\"")
  expect_match(corr_text, "\"输出与导出\"")
  expect_match(corr_text, "tabPanel\\(\\s*\"核心映射\"")
  expect_match(corr_text, "tabPanel\\(\\s*\"分组/分面/轨道/附加变量\"")
  expect_match(corr_text, "tabPanel\\(\\s*\"标题与说明\"")
  expect_match(corr_text, "tabPanel\\(\\s*\"显示与坐标\"")
  expect_match(corr_text, "tabPanel\\(\\s*\"图层样式\"")
  expect_match(corr_text, "tabPanel\\(\\s*\"参考线与阈值\"")
  expect_match(corr_text, "tabPanel\\(\\s*\"尺寸与画布\"")
  expect_match(corr_text, "tabPanel\\(\\s*\"导出参数\"")
  expect_match(corr_text, "title = \"结果区\"")
  expect_match(corr_text, "tabPanel\\(\\s*\"交互图\"")
  expect_match(corr_text, "tabPanel\\(\\s*\"数据\"")
  expect_match(combo_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(combo_text, "graphics_output_action_bar_ui\\(")
  expect_match(combo_text, "\"数据与变量\"")
  expect_match(combo_text, "\"图形与样式\"")
  expect_match(combo_text, "\"输出与导出\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"核心映射\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"分组/分面/轨道/附加变量\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"标题与说明\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"显示与坐标\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"图层样式\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"参考线与阈值\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"尺寸与画布\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"导出参数\"")
  expect_match(combo_text, "title = \"结果区\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"静态图\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"交互图\"")
  expect_match(combo_text, "tabPanel\\(\\s*\"数据\"")
  expect_match(forest_text, "\"数据与变量\"")
  expect_match(forest_text, "\"图形与样式\"")
  expect_match(forest_text, "\"输出与导出\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"核心映射\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"分组/分面/轨道/附加变量\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"标题与说明\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"显示与坐标\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"图层样式\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"参考线\"")
  expect_no_match(forest_text, "tabPanel\\(\\s*\"参考线与阈值\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"尺寸与画布\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"导出参数\"")
  expect_match(forest_text, "graphics_output_action_bar_ui\\(")
  expect_match(forest_text, "title = \"结果区\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"静态图\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"交互图\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"数据\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"数据预览\"")
  expect_match(forest_text, "tabPanel\\(\\s*\"统计报告\"")
  expect_match(forest_text, "graphics_table_panel_ui\\(")
  expect_match(forest_text, "graphics_text_label_panel_ui\\(")
  expect_match(forest_text, "graphics_axis_range_controls_ui\\(")
  expect_match(forest_text, "graphics_axis_tick_format_controls_ui\\(")
  expect_match(forest_text, "graphics_palette_layout_panel_ui\\(")
  expect_match(forest_text, "graphics_export_panel_ui\\(")
  expect_match(forest_text, "forest_result_data <- reactive\\(")
  expect_match(forest_text, "df <- forest_result_data\\(\\)")
  expect_match(forest_text, "exclude_ids = c\\(")
  expect_match(forest_text, "exclude_patterns = forest_task_state_exclude_patterns")
  expect_match(forest_text, "\"subgroup_col\", \"study_col\", \"estimate_col\", \"lower_col\", \"upper_col\"")
  expect_match(forest_text, "\"time_col\", \"status_col\", \"outcome_col\", \"covariates\"")
  expect_match(forest_text, "list\\(input_state = input_state, extra_state = list\\(\\)\\)")
  expect_match(forest_text, "forest_restore_selected_column_state\\(")
  expect_match(forest_text, "pending_mapping_restore <- reactiveVal\\(NULL\\)")
  expect_match(forest_text, "forest_build_mapping_restore_plan\\(")
  expect_match(forest_table_state_text, "forest_restore_selected_column_state <- function")
  expect_match(forest_table_state_text, "forest_can_restore_mapping_state <- function")
  expect_match(forest_table_state_text, "forest_build_mapping_restore_plan <- function")
  expect_match(forest_result_helper_text, "forest_normalize_result_schema <- function")
  expect_match(forest_result_helper_text, "forest_extract_model_result <- function")
  expect_match(forest_result_helper_text, "forest_finalize_analysis_results <- function")
  expect_match(forest_model_helper_text, "forest_prepare_analysis_dataframe <- function")
  expect_match(forest_model_helper_text, "forest_build_model_formula <- function")
  expect_match(forest_model_helper_text, "forest_fit_analysis_model <- function")
  expect_match(forest_pipeline_helper_text, "forest_run_analysis_pipeline <- function")
  expect_match(forest_text, "forest_run_analysis_pipeline\\(")
  expect_match(waterfall_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(waterfall_text, "graphics_display_legend_panel_ui\\(")
  expect_match(waterfall_text, "graphics_output_action_bar_ui\\(")
  expect_match(waterfall_text, "graphics_symbol_style_panel_ui\\(")
  expect_match(waterfall_text, "graphics_palette_layout_panel_ui\\(")
  expect_match(waterfall_text, "graphics_axis_proportion_panel_ui\\(")
  expect_match(waterfall_text, "graphics_group_style_mapping_panel_ui\\(")
  expect_match(waterfall_text, "graphics_reference_threshold_panel_ui\\(")
  expect_match(waterfall_text, "\"数据与变量\"")
  expect_match(waterfall_text, "\"图形与样式\"")
  expect_match(waterfall_text, "\"输出与导出\"")
  expect_match(waterfall_text, "tabPanel\\(\\s*\"核心映射\"")
  expect_match(waterfall_text, "tabPanel\\(\\s*\"分组/分面/轨道/附加变量\"")
  expect_match(waterfall_text, "\"标题与说明\"")
  expect_match(waterfall_text, "\"显示与坐标\"")
  expect_match(waterfall_text, "\"图层样式\"")
  expect_match(waterfall_text, "\"参考线与阈值\"")
  expect_match(waterfall_text, "\"尺寸与画布\"")
  expect_match(waterfall_text, "\"导出参数\"")
  expect_match(waterfall_text, "graphics_card_panel_ui\\(\\s*\"排序与轨道\"")
  expect_match(waterfall_text, "graphics_card_panel_ui\\(\\s*\"轨道与缺失值\"")
  expect_match(waterfall_text, "title = \"结果区\"")
  expect_match(waterfall_text, "tabPanel\\(\\s*\"交互图\"")
  expect_match(waterfall_text, "tabPanel\\(\\s*\"数据\"")
  expect_match(waterfall_text, "tabPanel\\(\\s*\"瀑布数据\"")
  expect_match(waterfall_text, "tabPanel\\(\\s*\"分组轨道数据\"")
  expect_match(waterfall_text, "graphics_text_label_panel_ui\\(")
  expect_match(survival_text, "graphics_column_mapping_panel_ui\\(")
  expect_match(survival_text, "graphics_text_label_panel_ui\\(")
  expect_match(survival_text, "\"数据与变量\"")
  expect_match(survival_text, "\"图形与样式\"")
  expect_match(survival_text, "\"输出与导出\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"核心映射\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"分组/分面/轨道/附加变量\"")
  expect_match(survival_text, "graphics_card_panel_ui\\(\\s*\"处理与筛选\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"标题与说明\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"显示与坐标\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"图层样式\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"参考线与阈值\"")
  expect_match(survival_text, "do.call\\(\\s*tabsetPanel")
  expect_match(survival_text, "graphics_card_panel_ui\\(\\s*\"曲线、删失点与风险表\"")
  expect_match(survival_text, "graphics_card_panel_ui\\(\\s*\"统计标注与位置\"")
  expect_match(survival_text, "graphics_card_panel_ui\\(\\s*\"图形与图例文字\"")
  expect_match(survival_text, "graphics_card_panel_ui\\(\\s*\"风险表文字\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"尺寸与画布\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"导出参数\"")
  expect_match(survival_text, "graphics_output_action_bar_ui\\(")
  expect_match(survival_text, "title = \"结果区\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"交互图\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"数据\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"数据表\"")
  expect_match(survival_text, "tabPanel\\(\\s*\"统计报告\"")
  expect_match(survival_text, "中位生存辅助线")
  expect_match(survival_text, "显示中位生存时间文本标注")
  expect_match(survival_text, "显示统计摘要（Log-rank P；分层时附加 HR）")
  expect_match(survival_text, "显示 Cox 回归 P值")
  expect_match(survival_text, "仅在未分层时生效；统一用于主图图例、风险表、数据表与统计报告")
  expect_match(survival_text, "统计摘要中的 HR 以")
  expect_match(survival_text, "交互式生存曲线")
  expect_no_match(survival_text, "else if \\(!is.null\\(input\\$time_range\\)")
})

test_that("第二批抽象第一版提供动态映射行容器并接入泳道图事件映射", {
  expect_match(common_ui_text, "graphics_dynamic_mapping_rows_panel_ui <- function")
  expect_match(common_ui_text, "graphics_dynamic_mapping_fields_ui <- function")
  expect_match(common_ui_text, "graphics_build_overlay_point_layer_fields_spec <- function")
  expect_match(common_ui_text, "graphics_build_event_mapping_fields_spec <- function")
  swimmer_path <- file.path(project_root, "modules", "statistical_graphics", "swimmer_plot.R")
  swimmer_text <- paste(readLines(swimmer_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(swimmer_text, "graphics_dynamic_mapping_rows_panel_ui\\(")
  expect_match(swimmer_text, "graphics_dynamic_mapping_fields_ui\\(session\\$ns, event_row_fields\\)")
  expect_match(swimmer_text, "graphics_build_overlay_point_layer_fields_spec\\(")
  expect_match(swimmer_text, "title = \"事件映射\"")
  expect_match(swimmer_text, "add_button_id = \"add_event_map\"")
  expect_match(swimmer_text, "remove_button_id = \"remove_event_map\"")
  expect_match(swimmer_text, "tabPanel\\(\\s*\"核心映射\"")
  expect_match(swimmer_text, "tabPanel\\(\\s*\"分组/分面/轨道/附加变量\"")
  expect_match(swimmer_text, "title = \"轨道变量与排序\"")
  expect_match(swimmer_text, "默认不自动填入轨道变量")
  expect_match(swimmer_text, "\"标题与说明\"")
  expect_match(swimmer_text, "\"显示与坐标\"")
  expect_match(swimmer_text, "\"图层样式\"")
  expect_match(swimmer_text, "title = \"轨道显示\"")
  expect_match(swimmer_text, "title = \"缺失值与版式\"")
  expect_match(swimmer_text, "轨道默认展示方式")
  expect_match(swimmer_text, "这里设置的是新选轨道的默认展示方式")
  expect_match(swimmer_text, "泳道终点-降序")
  expect_match(swimmer_text, "泳道终点-升序")
  expect_match(swimmer_text, "这里的“泳道终点”指换算后的随访终点位置")
  expect_match(swimmer_text, "事件总图例标题")
  expect_match(swimmer_text, "这里控制事件图例整体层级")
  expect_match(swimmer_text, "轨道总图例标题")
  expect_match(swimmer_text, "这里控制下方分组轨道区的显示方式与总图例标题")
  expect_match(swimmer_text, "下方轨道区占比")
  expect_match(swimmer_text, "“空值显示方式”影响轨道和数据表中的缺失文本")
  expect_match(swimmer_text, "“下方轨道区占比”和“全局字号”影响主图与下方轨道区的版式比例")
})

test_that("瀑布图高动态控件恢复与轨道区文案边界被锁定", {
  waterfall_path <- file.path(project_root, "modules", "statistical_graphics", "waterfall_plot.R")
  waterfall_text <- paste(readLines(waterfall_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(waterfall_text, "graphics_card_panel_ui\\(\\s*\"排序与轨道\"")
  expect_match(waterfall_text, "默认不自动填入轨道变量")
  expect_match(waterfall_text, "下方轨道区占比")
  expect_match(waterfall_text, "这里控制下方轨道区的颜色、文本显示和缺失值文本")
  expect_match(waterfall_text, "柱顶符号文本分组\\(可选\\)")
  expect_match(waterfall_text, "显示柱顶符号文本")
  expect_match(waterfall_text, "Y轴标签按百分比格式显示")
  expect_match(waterfall_text, "标签带百分号\\(%\\)")
  expect_match(waterfall_text, "这里只控制 Y 轴标签的显示格式，不会对原始变化值重新换算")
  expect_match(waterfall_text, "柱分组图例标题")
  expect_match(waterfall_text, "默认符号文本颜色")
  expect_match(waterfall_text, "符号文本大小")
  expect_match(waterfall_text, "轨道总图例标题")
  expect_match(waterfall_text, "outputOptions\\(output, \"bar_color_controls\", suspendWhenHidden = FALSE\\)")
  expect_match(waterfall_text, "outputOptions\\(output, \"symbol_controls\", suspendWhenHidden = FALSE\\)")
  expect_match(waterfall_text, "outputOptions\\(output, \"track_mode_controls\", suspendWhenHidden = FALSE\\)")
  expect_match(waterfall_text, "outputOptions\\(output, \"track_color_controls\", suspendWhenHidden = FALSE\\)")
  expect_no_match(waterfall_text, "pick_default_tracks <- function")
  expect_no_match(waterfall_text, "selected_tracks <- pick_default_tracks\\(")
})

test_that("瀑布图提交态快照与轨道区布局收口被锁定", {
  waterfall_path <- file.path(project_root, "modules", "statistical_graphics", "waterfall_plot.R")
  waterfall_text <- paste(readLines(waterfall_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(waterfall_text, "committed_params <- reactiveVal\\(NULL\\)")
  expect_match(waterfall_text, "build_waterfall_committed_params <- function")
  expect_match(waterfall_text, "collect_reference_line_spec_from_params <- function")
  expect_match(waterfall_text, "params <- committed_params\\(\\)")
  expect_match(waterfall_text, "params <- build_waterfall_committed_params\\(df\\)")
  expect_match(waterfall_text, "committed_params\\(params\\)")
  expect_match(waterfall_text, "committed_params\\(NULL\\)")
  expect_match(waterfall_text, "show_tracks <- if \\(is.list\\(params\\)")
  expect_match(waterfall_text, "geom_col\\(width = params\\$bar_width, color = params\\$bar_border_color\\)")
  expect_match(waterfall_text, "format_missing_vec\\(\\.track_value, params = params\\)")
  expect_match(waterfall_text, "graphics_compose_caption\\(params\\$plot_caption %\\|\\|% \"\", auto_caption_lines\\)")
  expect_match(waterfall_text, "collect_reference_line_spec_from_params\\(params, \"recist_lower\"")
  expect_match(waterfall_text, "position = params\\$main_legend_position %\\|\\|% \"right\"")
  expect_match(waterfall_text, "position = params\\$track_legend_position %\\|\\|% \"right\"")
  expect_match(waterfall_text, "检测到重复受试者ID，当前按既定口径自动保留每位受试者第一条记录；后续排序、轨道区和导出结果均基于保留后的记录。")
})

test_that("蜘蛛图提交态快照与尺寸链路收口被锁定", {
  spider_path <- file.path(project_root, "modules", "statistical_graphics", "spider_plot.R")
  spider_text <- paste(readLines(spider_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(spider_text, "committed_params <- reactiveVal\\(NULL\\)")
  expect_match(spider_text, "build_spider_committed_params <- function")
  expect_match(spider_text, "resolve_spider_size_config <- function")
  expect_match(spider_text, "committed_size_config <- reactive\\(")
  expect_match(spider_text, "collect_reference_line_spec_from_params <- function")
  expect_match(spider_text, "params <- build_spider_committed_params\\(df\\)")
  expect_match(spider_text, "committed_params\\(params\\)")
  expect_match(spider_text, "committed_params\\(NULL\\)")
  expect_match(spider_text, "cfg <- committed_size_config\\(\\)")
  expect_match(spider_text, "unit_divisor <- switch\\(params\\$time_unit")
  expect_match(spider_text, "geom_line\\(linewidth = params\\$line_size, alpha = params\\$line_alpha")
  expect_match(spider_text, "graphics_apply_x_break_step\\(p, plot_df\\$\\.time_plot, params\\$x_break_step\\)")
  expect_match(spider_text, "collect_reference_line_spec_from_params\\(params, \"recist_lower\"")
  expect_match(spider_text, "position = params\\$legend_position %\\|\\|% \"right\"")
})

test_that("蜘蛛图语义文案与 tooltip 格式被锁定", {
  spider_path <- file.path(project_root, "modules", "statistical_graphics", "spider_plot.R")
  spider_text <- paste(readLines(spider_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(spider_text, "Y轴标签按百分比格式显示")
  expect_match(spider_text, "标签带百分号\\(%\\)")
  expect_match(spider_text, "这里只控制 Y 轴标签显示格式，不会对原始变化值重新换算")
  expect_match(spider_text, "显示每条轨迹末次受试者标签")
  expect_match(spider_text, "为每条轨迹补充基线原点\\(time=0, value=0\\)")
  expect_match(spider_text, "graphics_format_percent_labels\\(")
  expect_match(spider_text, "graphics_format_number_labels\\(decimals = params\\$y_decimals %\\|\\|% 1\\)\\(plot_df\\$\\.value\\)")
})

test_that("泳道图任务历史显式保存并恢复动态样式状态", {
  swimmer_path <- file.path(project_root, "modules", "statistical_graphics", "swimmer_plot.R")
  swimmer_text <- paste(readLines(swimmer_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(swimmer_text, "capture_lane_manual_color_values <- function")
  expect_match(swimmer_text, "capture_track_mode_map <- function")
  expect_match(swimmer_text, "capture_track_color_values <- function")
  expect_match(swimmer_text, "capture_event_style_snapshot <- function")
  expect_match(swimmer_text, "restore_swimmer_dynamic_style_inputs <- function")
  expect_match(swimmer_text, "track_mode_map = track_mode_map")
  expect_match(swimmer_text, "lane_manual_colors = capture_lane_manual_color_values")
  expect_match(swimmer_text, "track_color_values = capture_track_color_values")
  expect_match(swimmer_text, "capture_event_style_snapshot\\(i, df_current\\)")
  expect_match(swimmer_text, "collect_swimmer_event_mappings <- function")
  expect_match(swimmer_text, "event_mappings = collect_swimmer_event_mappings\\(df_current\\)")
  expect_match(swimmer_text, "SwimmerApplyStateDynamicStyleError")
})

test_that("analysis_states 同时写入运行时建表与初始化 SQL", {
  expect_match(auth_text, "CREATE TABLE IF NOT EXISTS analysis_states")
  expect_match(sql_text, "CREATE TABLE IF NOT EXISTS analysis_states")
  expect_match(auth_text, "state_note TEXT")
  expect_match(sql_text, "state_note TEXT")
  expect_match(auth_text, "idx_analysis_states_user_scope")
  expect_match(sql_text, "idx_analysis_states_user_scope")
})

test_that("生存图删失点样式开始复用共享点形状枚举", {
  survival_path <- file.path(project_root, "modules", "statistical_graphics", "survival_analysis.R")
  survival_text <- paste(readLines(survival_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(survival_text, "graphics_point_shape_choices\\(\\)")
  expect_match(survival_text, "strata_labels = graphics_state\\$strata_labels %\\|\\|% list\\(\\)")
  expect_match(survival_text, "if \\(is.list\\(extra_state\\$strata_labels\\)\\) graphics_state\\$strata_labels <- extra_state\\$strata_labels")
  expect_match(survival_text, "\\.survival_strata_label_input_id\\(label_name\\)")
  expect_match(survival_text, "km_show_censor = input\\$km_show_censor")
  expect_match(survival_text, "plot_title = input\\$plot_title")
  expect_match(survival_text, "plot_caption = input\\$plot_caption")
  expect_match(survival_text, "if \\(isTRUE\\(params\\$km_show_censor\\)\\)")
  expect_match(survival_text, "output\\$survival_report <- renderUI\\(")
  expect_match(survival_text, "params <- committed_params\\(\\)")
  expect_match(survival_text, "if \\(isTRUE\\(params\\$show_median\\) && !is.null\\(med\\)")
  expect_match(survival_text, "show_cox_p = input\\$show_cox_p")
  expect_match(survival_text, "hr_lines <- if \\(isTRUE\\(params\\$show_stats\\)\\)")
  expect_match(survival_text, "summary_items <- c\\(median_lines, hr_lines\\)")
  expect_no_match(survival_text, "tags\\$div\\(\\s*class = \"panel panel-default\",\\s*tags\\$div\\(class = \"panel-heading\", \"图例与文字\"")
})

test_that("阶段性收口清单与代表模块 raw panel 基线被锁定", {
  guide_path <- file.path(project_root, "docs", "main", "PROJECT_GUIDE.md")
  guide_text <- paste(readLines(guide_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(guide_text, "阶段性收口清单（代表模块）")
  expect_match(guide_text, "`spider_plot\\.R`：普通设置型面板已全部切换到 common；剩余 raw panel `0`。")
  expect_match(guide_text, "`waterfall_plot\\.R`：普通设置型面板已全部切换到 common；剩余 raw panel `0`。")
  expect_match(guide_text, "`swimmer_plot\\.R`：普通设置型面板已全部切换到 common；剩余 raw panel `0`。")
  expect_match(guide_text, "`spider_plot\\.R`：普通面板已全部切换到 common，committed 参数快照已落地，三卡外层已回正。")
  expect_match(guide_text, "`swimmer_plot\\.R`：committed 参数快照已落地，事件映射恢复链路已修复，三卡外层已回正。")
  expect_match(guide_text, "`waterfall_plot\\.R`：committed 参数快照已落地，普通面板已全部切换到 common，三卡外层已回正。")
  expect_match(guide_text, "`survival_analysis\\.R`：committed 参数边界已收紧，统计语义文案已明确，三卡外层已回正。")
  expect_match(guide_text, "`modules/common/auth/`、`modules/common/data/`、`modules/common/analysis/`、`modules/common/graphics/`、`modules/common/export/`")
  expect_match(guide_text, "后端服务层/服务域.*账号认证、权限、会话、workspace")
  expect_match(guide_text, "`graphics_build_task_state\\(\\)` 保存 `data_mode`、列映射、原始数据分析字段、表格列选择、列显示名/对齐方式及导出参数")
  expect_match(guide_text, "Spider 当前开始采用 committed 输出口径")
  expect_match(guide_text, "Spider 第三轮继续做 UI 归类收紧")
  expect_match(guide_text, "统一参数面板布局规范")
  expect_match(guide_text, "同层级功能卡片优先合并为页签组")
  expect_match(guide_text, "3 个顶层功能卡片 \\+ 卡片内部子页签 \\+ 独立结果区")
  expect_match(guide_text, "`数据与变量 / 图形与样式 / 输出与导出` 这 3 个顶层功能卡本身做成并列页签")
  expect_match(guide_text, "结果页签：`静态图 / 交互图 / 数据 / 可复现代码`")
  expect_match(guide_text, "`graphics_output_action_bar_ui\\(\\)`：承载结果区顶部的 `生成图形 / 下载图形` 动作条")
  expect_match(guide_text, "`use_percent_label` 只影响 Y 轴标签与 tooltip 的显示格式")
  expect_match(guide_text, "`show_end_labels` 当前显示的是每条轨迹末次点对应的受试者标签")
  expect_match(guide_text, "当前控制的是柱顶文本符号映射，不是点形状图层")
  expect_match(guide_text, "`legend_title` 仅作用于主图柱分组图例")
  expect_match(guide_text, "当前表示按汇总后的“泳道终点”排序")
  expect_match(guide_text, "下一轮优先级")

  spider_path <- file.path(project_root, "modules", "statistical_graphics", "spider_plot.R")
  swimmer_path <- file.path(project_root, "modules", "statistical_graphics", "swimmer_plot.R")
  waterfall_path <- file.path(project_root, "modules", "statistical_graphics", "waterfall_plot.R")
  spider_text <- paste(readLines(spider_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  swimmer_text <- paste(readLines(swimmer_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  waterfall_text <- paste(readLines(waterfall_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

  expect_equal(length(gregexpr("panel panel-default", spider_text, fixed = TRUE)[[1]][gregexpr("panel panel-default", spider_text, fixed = TRUE)[[1]] > 0]), 0)
  expect_equal(length(gregexpr("panel panel-default", waterfall_text, fixed = TRUE)[[1]][gregexpr("panel panel-default", waterfall_text, fixed = TRUE)[[1]] > 0]), 0)
  expect_equal(length(gregexpr("panel panel-default", swimmer_text, fixed = TRUE)[[1]][gregexpr("panel panel-default", swimmer_text, fixed = TRUE)[[1]] > 0]), 0)
  expect_match(swimmer_text, "graphics_dynamic_mapping_row_ui\\(")
  expect_match(swimmer_text, "paste0\\(\"事件变量组 \", i\\)")
})

test_that("森林图目录拆分目标在 PROJECT_SPEC 中被锁定", {
  spec_path <- file.path(project_root, "docs", "main", "PROJECT_SPEC.md")
  spec_text <- paste(readLines(spec_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

  expect_match(spec_text, "图形共享层")
  expect_match(spec_text, "参考线抽象")
  expect_match(spec_text, "森林图")
  expect_match(spec_text, "workspace 为空时保存为个人任务")
  expect_match(spec_text, "workspace 创建、成员授权、Owner 迁移等写操作必须从 service 层进入")
  expect_no_match(spec_text, "modules/server/statistical_graphics/")
})

test_that("analysis_states service 对个人任务使用 NULL workspace SQL 分支", {
  account_service_path <- file.path(project_root, "modules", "common", "auth", "account_service.R")
  account_text <- paste(readLines(account_service_path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  expect_match(account_text, "service_build_analysis_state_insert_spec")
  expect_match(account_text, "VALUES \\(\\$1, \\$2, NULL, \\$3, \\$4, \\$5, \\$6, \\$7, NOW\\(\\), NOW\\(\\)\\)")
  expect_match(account_text, "service_delete_analysis_state")
  expect_match(account_text, "match_workspace = TRUE")
})



