# AutoTFL R package manifest.
# Scripts should source this file instead of maintaining parallel package lists.

autotfl_required_packages <- function() {
  c(
    "shiny",
    "shinydashboard",
    "shinyjs",
    "shinyBS",
    "bslib",
    "shinyWidgets",
    "waiter",
    "shinyalert",
    "dplyr",
    "readr",
    "readxl",
    "haven",
    "jsonlite",
    "purrr",
    "stringr",
    "memoise",
    "ggplot2",
    "plotly",
    "DT",
    "gt",
    "patchwork",
    "reactable",
    "cowplot",
    "gridExtra",
    "scales",
    "RColorBrewer",
    "showtext",
    "sysfonts",
    "cards",
    "gtsummary",
    "tfrmt",
    "forcats",
    "tidyr",
    "rlang",
    "rtables",
    "tern",
    "survival",
    "broom",
    "survminer",
    "corrplot",
    "DBI",
    "RPostgres",
    "pool",
    "ggsci",
    "colourpicker",
    "digest",
    "curl",
    "rlistings",
    "r2rtf",
    "rmarkdown",
    "webshot2",
    "knitr",
    # pagedown — 可选依赖：表格 PDF 导出已改为 R 原生 cairo_pdf 路径，不再需要 Chromium。
    # 如将来需要 chrome_print 功能（如复杂 HTML→PDF），可取消注释。
    # "pagedown",
    "flextable",
    "officer",
    "svglite",
    "testthat",
    "lintr",
    "styler",
    "shinytest2",
    "shinyFiles"
  )
}

REQUIRED_PACKAGES <- autotfl_required_packages()
