test_find_project_root <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- "--file="
  script_path <- sub(file_arg, "", args[grep(file_arg, args)])
  script_path <- if (length(script_path) > 0) script_path[[1]] else ""
  start_candidates <- unique(c(
    if (nzchar(script_path)) dirname(normalizePath(script_path, winslash = "/", mustWork = FALSE)) else character(0),
    normalizePath(getwd(), winslash = "/", mustWork = FALSE)
  ))

  for (candidate in start_candidates) {
    current <- candidate
    repeat {
      if (file.exists(file.path(current, "app.R")) &&
          dir.exists(file.path(current, "modules")) &&
          dir.exists(file.path(current, "tests"))) {
        return(normalizePath(current, winslash = "/", mustWork = TRUE))
      }
      parent <- dirname(current)
      if (identical(parent, current)) break
      current <- parent
    }
  }

  stop("无法定位项目根目录。", call. = FALSE)
}

project_root <- test_find_project_root()
setwd(file.path(project_root, "tests"))
args <- commandArgs(trailingOnly = FALSE)
file_arg <- "--file="
script_path <- sub(file_arg, "", args[grep(file_arg, args)])
script_dir <- dirname(normalizePath(script_path, winslash = "/", mustWork = FALSE))
project_root <- test_find_project_root()

read_utf8 <- function(...) {
  file_path <- file.path(project_root, ...)
  if (length(file_path) == 0 || !file.exists(file_path)) return("")
  paste(readLines(file_path, encoding = "UTF-8", warn = FALSE), collapse = "\n")
}
database_manager_text <- read_utf8("modules", "database_manager.R")
if (!nzchar(database_manager_text)) return(invisible(NULL))
readme_text <- read_utf8("README.md")
guide_text <- read_utf8("docs", "main", "PROJECT_GUIDE.md")
spec_text <- read_utf8("docs", "main", "PROJECT_SPEC.md")
test_guide_text <- read_utf8("docs", "main", "TEST_GUIDE.md")
deployment_text <- read_utf8("docs", "deploy", "DEPLOY_GUIDE.md")
compose_local_text <- read_utf8("docker-compose.local.yml")
compose_temp_text <- read_utf8("docker-compose1.yml")
compose_server_text <- read_utf8("docker-compose.server.yml")
env_example_text <- read_utf8("deploy", "alicloud", "env", ".env.example")
test_env_example_text <- read_utf8(".env.test.example")

expect_contains <- function(text, pattern, label, fixed = FALSE) {
  matched <- if (fixed) {
    grepl(pattern, text, fixed = TRUE)
  } else {
    grepl(pattern, text, perl = TRUE)
  }
  if (!matched) {
    stop(sprintf("缺少预期内容: %s", label), call. = FALSE)
  }
}

expect_not_contains <- function(text, pattern, label) {
  if (grepl(pattern, text, perl = TRUE)) {
    stop(sprintf("发现应移除内容: %s", label), call. = FALSE)
  }
}

expect_contains(database_manager_text, "从服务器目录导入数据空间", "数据库管理模块导入入口文案")
expect_contains(database_manager_text, "请输入服务器或容器可见的绝对路径", "数据库管理模块导入占位提示")
expect_contains(database_manager_text, "当前仅支持导入部署机器可见目录，不支持直接读取浏览器所在电脑的本地文件夹。", "数据库管理模块导入边界说明")
expect_contains(database_manager_text, "该入口当前仅面向系统管理员开放；多用户能力落地前不面向普通用户开放。", "数据库管理模块管理员限定说明")
expect_contains(database_manager_text, "service_create_workspace\\(", "数据库管理模块通过 service 创建 workspace")
expect_contains(database_manager_text, "service_delete_workspace\\(", "数据库管理模块通过 service 删除 workspace")
expect_contains(database_manager_text, "当前账号无权管理该数据空间", "数据库管理模块 workspace 管理权限提示")
expect_contains(database_manager_text, "数据库管理功能尚未开放，请联系系统管理员授权", "数据库管理模块数据库锁提示")
expect_contains(database_manager_text, "db_access_enabled", "数据库管理模块依赖数据库管理权限字段")
expect_contains(database_manager_text, "title = \"数据空间管理\"", "数据库管理模块阶段二主标题")
expect_contains(database_manager_text, "\"空间与目录\"", "数据库管理模块阶段二空间与目录标签")
expect_contains(database_manager_text, "\"上传与导入\"", "数据库管理模块阶段二上传与导入标签")
expect_contains(database_manager_text, "\"结构总览\"", "数据库管理模块阶段二结构总览标签")
expect_not_contains(database_manager_text, "从本地文件夹导入数据空间", "数据库管理模块旧导入文案")

expect_contains(readme_text, "当前 `/app/` 已实现应用内自注册、登录、退出与 workspace 级权限过滤。", "README 访问控制边界")
expect_contains(readme_text, "登录、注册与忘记密码已拆为独立页面状态", "README 登录注册说明")
expect_contains(readme_text, "登录页底部提供“注册账号 / 忘记密码”入口", "README 登录页快捷入口说明")
expect_contains(readme_text, "按钮式次级操作", "README 登录页次级操作可见性说明")
expect_contains(readme_text, "EMAIL_DELIVERY_MODE=console", "README 邮箱验证 console 投递说明")
expect_contains(readme_text, "邮箱验证已移到登录后的用户信息区", "README 邮箱验证位置说明")
expect_contains(readme_text, "用户和权限", "README 用户和权限入口说明")
expect_contains(readme_text, "修改密码", "README 修改密码说明")
expect_contains(readme_text, "用户信息` 页只保留基础用户信息与少量信息变更控件", "README 用户信息精简说明")
expect_contains(readme_text, "Owner 会看到 workspace 协作权限管理卡", "README Owner 权限管理说明")
expect_contains(readme_text, "我的已授权空间", "README 普通成员授权信息卡说明")
expect_contains(readme_text, "非空态说明", "README 无空间非空态说明")
expect_contains(readme_text, "忘记密码已改为独立找回页", "README 密码重置说明")
expect_contains(readme_text, "AUTH_PASSWORD_RESET_EXPIRE_MINUTES", "README 密码重置过期时间说明")
expect_contains(readme_text, "已支持登录后邮箱换绑", "README 邮箱换绑说明")
expect_contains(readme_text, "自动尝试认领该邮箱名下待领取的协作邀请", "README 邮箱换绑邀请认领说明")
expect_contains(readme_text, "email_service.R", "README 邮件服务模块说明")
expect_contains(readme_text, "SMTP_HOST", "README SMTP 配置说明")
expect_contains(readme_text, "SMTP 连通性测试", "README SMTP 探针说明")
expect_contains(readme_text, "最近一次探针结果", "README SMTP 探针最近结果说明")
expect_contains(readme_text, "认证主体区域已抽到 `auth_manager.R`；当前用户信息、退出入口与普通用户的“权限管理”快捷入口已合并到侧边栏卡片中。", "README 认证模块与侧边栏信息")
expect_contains(readme_text, "当前登录态会定时从数据库刷新用户状态与数据库管理开关", "README 用户会话刷新说明")
expect_contains(readme_text, "侧边栏用户卡片右上角快捷按钮现统一收口为：系统管理员固定跳转“系统管理”", "README 侧边栏快捷按钮规则")
expect_contains(readme_text, "未登录状态下仅显示登录/注册入口；进入工作台前不展示业务侧边栏。", "README 未登录入口说明")
expect_contains(readme_text, "当前工具声明为：不负责数据安全、数据传到服务不保证安全，请使用方自行妥善保管数据；如需更高保障，可提供独立部署服务。", "README 免责声明")
expect_contains(readme_text, "且该入口只面向系统管理员开放。", "README 管理员限定")
expect_contains(readme_text, "当前系统角色口径仅保留系统管理员与普通用户", "README 角色口径")
expect_contains(readme_text, "不得读取、浏览或导出其他用户数据空间中的实际数据", "README 服务层保密底线")
expect_contains(readme_text, "管理员账号必须通过环境变量预置 `APP_ADMIN_USERNAME`、`APP_ADMIN_EMAIL` 与 `APP_ADMIN_PASSWORD`；未配置时不自动提升首个注册用户。", "README 管理员环境变量说明")
expect_contains(readme_text, "管理员环境变量当前视为引导权威输入", "README 管理员环境变量同步说明")
expect_contains(readme_text, "workspace、membership、invite 与 owner 迁移能力已统一下沉到 service 层。", "README service 层说明")
expect_contains(readme_text, "workspace 创建与删除也统一复用 `modules/common/auth/account_service.R`", "README workspace service 收口说明")
expect_contains(readme_text, "普通用户可对自己拥有的数据空间进行权限管理，且授权、撤销与 owner 迁移统一通过邮箱输入完成", "README Owner 邮箱授权说明")
expect_contains(readme_text, "管理员页保持独立系统入口，不并入侧边栏用户卡片", "README 管理员入口独立说明")
expect_contains(readme_text, "管理员页现补充信息型增强：顶部系统概览、运行环境摘要、目标账号状态卡片、操作影响预览，以及“我名下数据空间概览”", "README 管理员信息增强说明")
expect_contains(readme_text, "管理员页前端展示现按“摘要优先、明细随后”收拢", "README 管理员前端收拢说明")
expect_contains(readme_text, "管理员页使用", "README 管理员页公共 UI 壳说明", fixed = TRUE)
expect_contains(readme_text, "账号状态管理已与“所有注册账号总览”联动", "README 管理员账号状态联动说明")
expect_contains(readme_text, "数据空间负责人迁移与协作授权现统一收口到单一“数据空间管理”卡片", "README 管理员数据空间管理收口说明")
expect_contains(readme_text, "系统概览、异常态势摘要与账号状态管理中的状态卡现统一切到紧凑统计卡布局", "README 管理员紧凑统计卡说明")
expect_contains(readme_text, "数据库管理页使用公共卡片壳", "README 数据库管理页公共 UI 壳说明")
expect_contains(readme_text, "统计分析总入口使用公共卡片壳", "README 统计分析总入口公共 UI 壳说明")
expect_contains(readme_text, "统计分析子模块样板覆盖 `desc.R` 与 `cox.R`", "README 统计分析子模块样板说明")
expect_contains(readme_text, "统计分析回归类子模块样板覆盖 `logistic.R` 与 `linear.R`", "README 统计分析回归类子模块样板说明")
expect_contains(readme_text, "统计分析基础检验子模块样板覆盖 `anova.R` 与 `chisq.R`", "README 统计分析基础检验子模块样板说明")
expect_contains(readme_text, "统计分析结果区已统一", "README 统计分析结果区统一说明")
expect_contains(readme_text, "第一批 UI 归一已接入公共扩散源", "README 第一批 UI 归一说明")
expect_contains(readme_text, "统计图形总入口使用公共卡片壳", "README 统计图形总入口公共壳说明")
expect_contains(readme_text, "箱线图外层使用公共卡片壳", "README 箱线图外层公共壳说明")
expect_contains(readme_text, "组合图外层使用公共卡片壳", "README 组合图外层公共壳说明")
expect_contains(readme_text, "生存分析外层使用公共卡片壳", "README 生存分析外层公共壳说明")
expect_contains(readme_text, "森林图外层使用公共卡片壳", "README 森林图外层公共壳说明")
expect_contains(readme_text, "蜘蛛图外层使用公共卡片壳", "README 蜘蛛图外层公共壳说明")
expect_contains(readme_text, "泳道图外层使用公共卡片壳", "README 泳道图外层公共壳说明")
expect_contains(readme_text, "瀑布图外层使用公共卡片壳", "README 瀑布图外层公共壳说明")
expect_contains(readme_text, "Tables 总入口使用公共卡片壳", "README Tables 总入口公共壳说明")
expect_contains(readme_text, "探索分析总入口使用公共卡片壳", "README 探索分析总入口公共壳说明")
expect_contains(readme_text, "管理员页现已补充“异常态势摘要”", "README 管理员异常态势摘要说明")
expect_contains(readme_text, "异常态势摘要现支持页内快捷跳转，可直接定位到账号状态管理、数据空间管理与我名下数据空间概览；在数据空间管理场景下可进一步聚焦负责人邮箱或协作者邮箱输入框，并在协作相关场景切换到相关预览 tab", "README 管理员异常态势摘要快捷跳转说明")
expect_contains(readme_text, "管理员页现已补充“所有注册账号总览”，通过摘要卡、预设筛选按钮与总览表结合的方式展示所有已注册账号的元信息", "README 管理员注册账号总览说明")
expect_contains(readme_text, "权限预览表与管理员 membership 预览表已改为面向业务的中文列名", "README 预览表中文列名说明")
expect_contains(readme_text, "数据库管理页已按“空间与目录 / 上传与导入 / 结构总览”三段重组", "README 数据库管理阶段二布局")
expect_contains(readme_text, "数据库管理功能已增加账号级访问锁", "README 数据库管理锁说明")
expect_contains(readme_text, "未开通数据空间功能的普通用户登录后默认落到“数据准备”页", "README 未开通数据空间功能默认落点")
expect_contains(readme_text, "普通用户在未开通数据空间功能时，只允许单文件临时上传；该数据仅用于当前会话分析，不写入持久化数据空间", "README 临时上传说明")
expect_contains(readme_text, "当前阶段风险与优化建议", "README 风险与优化建议章节")
expect_contains(readme_text, "tests/common/auth/test_auth_access_postgres_integration.R", "README PostgreSQL 集成测试文件")
expect_contains(readme_text, "tests/admin_manager/test_admin_manager_smoke_shinytest2.R", "README 管理员页 shinytest2 smoke test 文件")
expect_contains(readme_text, "tests/admin_manager/test_admin_manager_layout_guard.R", "README 管理员页布局守卫文件")
expect_contains(readme_text, "tests/account_access/test_account_access_smoke_shinytest2.R", "README 账号页 shinytest2 smoke test 文件")
expect_contains(readme_text, "tests/statistical_analysis/ui/test_statistical_analysis_layout_guard.R", "README 统计分析布局守卫文件")
expect_contains(readme_text, "tests/statistical_analysis/ui/test_statistical_analysis_submodule_ui_guard.R", "README 统计分析子模块 UI 守卫文件")
expect_contains(readme_text, "tests/statistical_analysis/ui/test_statistical_analysis_regression_submodule_ui_guard.R", "README 统计分析回归类子模块 UI 守卫文件")
expect_contains(readme_text, "tests/statistical_analysis/ui/test_statistical_analysis_basic_submodule_ui_guard.R", "README 统计分析基础检验子模块 UI 守卫文件")
expect_contains(readme_text, "tests/statistical_analysis/ui/test_statistical_analysis_result_ui_guard.R", "README 统计分析结果区 UI 守卫文件")
expect_contains(readme_text, "tests/common/ui/test_data_filter_card_ui_guard.R", "README data_filter UI 守卫文件")
expect_contains(readme_text, "tests/common/ui/test_task_history_card_ui_guard.R", "README task_history UI 守卫文件")
expect_contains(readme_text, "tests/statistical_graphics/ui/test_statistical_graphics_layout_guard.R", "README 统计图形入口 UI 守卫文件")
expect_contains(readme_text, "tests/statistical_graphics/boxplot/test_boxplot_layout_guard.R", "README 箱线图外层 UI 守卫文件")
expect_contains(readme_text, "tests/statistical_graphics/combo/test_combo_layout_guard.R", "README 组合图外层 UI 守卫文件")
expect_contains(readme_text, "tests/statistical_graphics/survival/test_survival_layout_guard.R", "README 生存分析外层 UI 守卫文件")
expect_contains(readme_text, "tests/statistical_graphics/forest/test_forest_layout_guard.R", "README 森林图外层 UI 守卫文件")
expect_contains(readme_text, "tests/statistical_graphics/spider/test_spider_layout_guard.R", "README 蜘蛛图外层 UI 守卫文件")
expect_contains(readme_text, "tests/statistical_graphics/swimmer/test_swimmer_layout_guard.R", "README 泳道图外层 UI 守卫文件")
expect_contains(readme_text, "tests/statistical_graphics/waterfall/test_waterfall_layout_guard.R", "README 瀑布图外层 UI 守卫文件")
expect_contains(readme_text, "tests/tables/test_tables_layout_guard.R", "README Tables 入口 UI 守卫文件")
expect_contains(readme_text, "tests/exploratory_analysis/test_exploratory_analysis_layout_guard.R", "README 探索分析入口 UI 守卫文件")
expect_contains(readme_text, "run_auth_regression.ps1", "README 账号模块统一回归入口")
expect_contains(readme_text, "公共卡片壳风格", "README UI 统一风格说明")
expect_contains(readme_text, "modules/common/ui_shell.R", "README UI 壳来源说明")
expect_contains(readme_text, "不再新增平行风格", "README UI 风格约束")
expect_contains(readme_text, "工具链建议：在现有 `tests/` 守卫测试之外持续维护基于 PostgreSQL 测试库的自动化回归", "README 工具链建议")
expect_contains(readme_text, "docker-compose.local.yml` 或 `docker-compose1.yml`", "README 测试端口说明")
expect_contains(readme_text, "`docker-compose.local.yml` 现直接读取 `.env.test`", "README local compose 读取 .env.test")
expect_contains(readme_text, "docker-compose1.yml` 当前收口为轻量测试基础设施栈", "README compose1 轻量测试基础设施说明")

expect_contains(guide_text, "当前仓库已实现应用内自注册、登录、退出与 workspace 级权限控制。", "PROJECT_GUIDE 访问控制边界")
expect_contains(guide_text, "modules/common/auth/auth_copy.R", "PROJECT_GUIDE 账号入口共享文案文件")
expect_contains(guide_text, "ACCOUNT_ENTRY_COPY", "PROJECT_GUIDE 账号入口共享文案对象")
expect_contains(guide_text, "登录支持用户名或邮箱；注册阶段会校验邮箱格式，当前登录、注册与忘记密码已拆为独立页面状态", "PROJECT_GUIDE 邮箱说明")
expect_contains(guide_text, "登录页底部提供“注册账号 / 忘记密码”入口", "PROJECT_GUIDE 登录页快捷入口说明")
expect_contains(guide_text, "按钮式次级操作", "PROJECT_GUIDE 登录页次级操作可见性说明")
expect_contains(guide_text, "EMAIL_DELIVERY_MODE=console", "PROJECT_GUIDE 邮箱验证 console 投递说明")
expect_contains(guide_text, "邮箱验证已移到登录后的用户信息区", "PROJECT_GUIDE 邮箱验证位置说明")
expect_contains(guide_text, "用户和权限", "PROJECT_GUIDE 用户和权限入口说明")
expect_contains(guide_text, "修改密码", "PROJECT_GUIDE 修改密码说明")
expect_contains(guide_text, "`user_profile` 只保留基础用户信息与少量信息变更控件", "PROJECT_GUIDE 用户信息精简说明")
expect_contains(guide_text, "`access_permissions` 按权限分支展示协作权限或“我的已授权空间”", "PROJECT_GUIDE Owner 权限管理说明")
expect_contains(guide_text, "我的已授权空间", "PROJECT_GUIDE 普通成员授权信息卡说明")
expect_contains(guide_text, "无可管理空间时必须提供非空态说明", "PROJECT_GUIDE 无空间非空态说明")
expect_contains(guide_text, "忘记密码已改为独立找回页", "PROJECT_GUIDE 密码重置说明")
expect_contains(guide_text, "AUTH_PASSWORD_RESET_EXPIRE_MINUTES", "PROJECT_GUIDE 密码重置过期时间说明")
expect_contains(guide_text, "已支持登录后邮箱换绑", "PROJECT_GUIDE 邮箱换绑说明")
expect_contains(guide_text, "自动尝试认领该邮箱名下待领取的协作邀请", "PROJECT_GUIDE 邮箱换绑邀请认领说明")
expect_contains(guide_text, "modules/common/auth/email_service.R", "PROJECT_GUIDE 邮件服务模块说明")
expect_contains(guide_text, "SMTP_HOST", "PROJECT_GUIDE SMTP 配置说明")
expect_contains(guide_text, "SMTP 连通性测试", "PROJECT_GUIDE SMTP 探针说明")
expect_contains(guide_text, "最近一次探针结果", "PROJECT_GUIDE SMTP 探针最近结果说明")
expect_contains(guide_text, "普通用户的两个快捷入口标签直接复用 `ACCOUNT_ENTRY_COPY\\$actions`", "PROJECT_GUIDE 侧边栏信息")
expect_contains(guide_text, "公共卡片壳风格", "PROJECT_GUIDE UI 统一风格说明")
expect_contains(guide_text, "modules/common/ui_shell.R", "PROJECT_GUIDE UI 壳来源说明")
expect_contains(guide_text, "不再新增平行风格", "PROJECT_GUIDE UI 风格约束")
expect_contains(guide_text, "当前登录态会定时从数据库刷新用户状态与数据库管理开关", "PROJECT_GUIDE 用户会话刷新说明")
expect_contains(guide_text, "按钮实际展示文案统一复用 `ACCOUNT_ENTRY_COPY\\$actions`", "PROJECT_GUIDE 侧边栏快捷按钮规则")
expect_contains(guide_text, "未登录状态下只渲染登录/注册入口，不渲染业务工作台侧边栏。", "PROJECT_GUIDE 未登录入口说明")
expect_contains(guide_text, "当前系统角色口径仅保留系统管理员与普通用户。", "PROJECT_GUIDE 角色口径")
expect_contains(guide_text, "可查看数据库信息与 workspace 元信息，但不得读取、浏览或导出其他用户数据空间中的实际数据", "PROJECT_GUIDE 管理员能力")
expect_contains(guide_text, "当前工具暂不负责数据安全；数据传到服务端后不保证安全，请使用方自行妥善保管数据。", "PROJECT_GUIDE 免责声明-安全")
expect_contains(guide_text, "管理员账号必须通过环境变量预置 `APP_ADMIN_USERNAME`、`APP_ADMIN_EMAIL` 与 `APP_ADMIN_PASSWORD`；未配置时不自动提升首个注册用户。", "PROJECT_GUIDE 管理员环境变量说明")
expect_contains(guide_text, "管理员环境变量当前视为引导权威输入", "PROJECT_GUIDE 管理员环境变量同步说明")
expect_contains(guide_text, "服务器目录导入只面向系统管理员开放；在多用户能力真正落地前，不应向普通用户开放该入口。", "PROJECT_GUIDE 管理员限定")
expect_contains(guide_text, "当前仓库尚未实现 ZIP 数据空间导入；文档与功能描述不得把该能力写成已支持。", "PROJECT_GUIDE ZIP 未落地说明")
expect_contains(guide_text, "当前已支持用户自注册，并保留系统管理员账号。", "PROJECT_GUIDE 自注册目标")
expect_contains(guide_text, "当前首期隔离粒度以“个人空间”为主，每个用户默认拥有独立数据空间边界。", "PROJECT_GUIDE 个人隔离目标")
expect_contains(guide_text, "数据权限首期落到 workspace 级别", "PROJECT_GUIDE workspace 权限目标")
expect_contains(guide_text, "普通用户在未开通数据空间功能时，只允许单文件临时上传；上传数据仅用于当前会话分析，不写入持久化数据空间。", "PROJECT_GUIDE 临时上传说明")
expect_contains(guide_text, "`modules/common/auth/account_service.R`", "PROJECT_GUIDE 服务层文件")
expect_contains(guide_text, "`modules/common/auth/auth.R`", "PROJECT_GUIDE 认证共享层文件")
expect_contains(guide_text, "`auth_manager.R`", "PROJECT_GUIDE 认证页面模块文件")
expect_contains(guide_text, "`modules/account_access/user_profile.R`", "PROJECT_GUIDE 用户信息模块文件")
expect_contains(guide_text, "`modules/account_access/permission_manager.R`", "PROJECT_GUIDE 权限管理模块文件")
expect_contains(guide_text, "`modules/account_access/sidebar_account_card.R`", "PROJECT_GUIDE 侧边栏账号卡模块文件")
expect_contains(guide_text, "workspace 创建与删除也统一通过 `modules/common/auth/account_service.R` 收口", "PROJECT_GUIDE workspace service 收口说明")
expect_contains(guide_text, "普通用户可对自己拥有的数据空间进行权限管理，且授权、撤销与 owner 迁移统一通过邮箱输入完成。", "PROJECT_GUIDE Owner 邮箱授权说明")
expect_contains(guide_text, "管理员页保持独立系统入口，不并入侧边栏用户卡片", "PROJECT_GUIDE 管理员入口独立说明")
expect_contains(guide_text, "管理员页现补充信息型增强：顶部系统概览、运行环境摘要、目标账号状态卡片、操作影响预览，以及“我名下数据空间概览”", "PROJECT_GUIDE 管理员信息增强说明")
expect_contains(guide_text, "管理员页前端展示现按“摘要优先、明细随后”收拢", "PROJECT_GUIDE 管理员前端收拢说明")
expect_contains(guide_text, "管理员页使用", "PROJECT_GUIDE 管理员页公共 UI 壳说明", fixed = TRUE)
expect_contains(guide_text, "账号状态管理已与“所有注册账号总览”联动", "PROJECT_GUIDE 管理员账号状态联动说明")
expect_contains(guide_text, "数据空间负责人迁移与协作授权现统一收口到单一“数据空间管理”卡片", "PROJECT_GUIDE 管理员数据空间管理收口说明")
expect_contains(guide_text, "系统概览、异常态势摘要与账号状态管理中的状态卡现统一切到紧凑统计卡布局", "PROJECT_GUIDE 管理员紧凑统计卡说明")
expect_contains(guide_text, "数据库管理页使用公共卡片壳", "PROJECT_GUIDE 数据库管理页公共 UI 壳说明")
expect_contains(guide_text, "统计分析总入口使用公共卡片壳", "PROJECT_GUIDE 统计分析总入口公共 UI 壳说明")
expect_contains(guide_text, "统计分析子模块样板覆盖 `desc.R` 与 `cox.R`", "PROJECT_GUIDE 统计分析子模块样板说明")
expect_contains(guide_text, "统计分析回归类子模块样板覆盖 `logistic.R` 与 `linear.R`", "PROJECT_GUIDE 统计分析回归类子模块样板说明")
expect_contains(guide_text, "统计分析基础检验子模块样板覆盖 `anova.R` 与 `chisq.R`", "PROJECT_GUIDE 统计分析基础检验子模块样板说明")
expect_contains(guide_text, "统计分析结果区已统一", "PROJECT_GUIDE 统计分析结果区统一说明")
expect_contains(guide_text, "第一批 UI 归一已接入公共扩散源", "PROJECT_GUIDE 第一批 UI 归一说明")
expect_contains(guide_text, "统计图形总入口使用公共卡片壳", "PROJECT_GUIDE 统计图形总入口公共壳说明")
expect_contains(guide_text, "箱线图外层使用公共卡片壳", "PROJECT_GUIDE 箱线图外层公共壳说明")
expect_contains(guide_text, "组合图外层使用公共卡片壳", "PROJECT_GUIDE 组合图外层公共壳说明")
expect_contains(guide_text, "生存分析外层使用公共卡片壳", "PROJECT_GUIDE 生存分析外层公共壳说明")
expect_contains(guide_text, "森林图外层使用公共卡片壳", "PROJECT_GUIDE 森林图外层公共壳说明")
expect_contains(guide_text, "蜘蛛图外层使用公共卡片壳", "PROJECT_GUIDE 蜘蛛图外层公共壳说明")
expect_contains(guide_text, "泳道图外层使用公共卡片壳", "PROJECT_GUIDE 泳道图外层公共壳说明")
expect_contains(guide_text, "瀑布图外层使用公共卡片壳", "PROJECT_GUIDE 瀑布图外层公共壳说明")
expect_contains(guide_text, "Tables 总入口使用公共卡片壳", "PROJECT_GUIDE Tables 总入口公共壳说明")
expect_contains(guide_text, "探索分析总入口使用公共卡片壳", "PROJECT_GUIDE 探索分析总入口公共壳说明")
expect_contains(guide_text, "管理员页现已补充“异常态势摘要”", "PROJECT_GUIDE 管理员异常态势摘要说明")
expect_contains(guide_text, "异常态势摘要现支持页内快捷跳转，可直接定位到账号状态管理、数据空间管理与我名下数据空间概览；在数据空间管理场景下可进一步聚焦负责人邮箱或协作者邮箱输入框，并在协作相关场景切换到相关预览 tab", "PROJECT_GUIDE 管理员异常态势摘要快捷跳转说明")
expect_contains(guide_text, "管理员页现已补充“所有注册账号总览”，通过摘要卡、预设筛选按钮与总览表结合的方式展示所有已注册账号的元信息", "PROJECT_GUIDE 管理员注册账号总览说明")
expect_contains(guide_text, "权限预览表统一改为业务中文列名；数据库管理页按“空间与目录 / 上传与导入 / 结构总览”三段重组。", "PROJECT_GUIDE 阶段二 UI 说明")
expect_contains(guide_text, "数据库管理功能已增加账号级访问锁", "PROJECT_GUIDE 数据库管理锁说明")
expect_contains(guide_text, "未开通数据空间功能的普通用户登录后默认落到“数据准备”页", "PROJECT_GUIDE 未开通数据空间功能默认落点")
expect_contains(guide_text, "当前尚未实现组织级、项目级隔离，也未提供更细粒度的 folder 或 dataset 权限模型。", "PROJECT_GUIDE 多用户路线")
expect_contains(guide_text, "当前阶段风险与优化建议", "PROJECT_GUIDE 风险与优化建议章节")
expect_contains(guide_text, "管理员初始化必须通过环境变量预置；当前不支持用“首个注册用户自动升级”为系统管理员。", "PROJECT_GUIDE 初始化要求")
expect_contains(guide_text, "tests/common/auth/test_auth_access_postgres_integration.R", "PROJECT_GUIDE PostgreSQL 集成测试文件")
expect_contains(test_guide_text, "tests/admin_manager/test_admin_manager_smoke_shinytest2.R", "TEST_GUIDE 管理员页 shinytest2 smoke test 文件")
expect_contains(test_guide_text, "tests/admin_manager/test_admin_manager_layout_guard.R", "TEST_GUIDE 管理员页布局守卫文件")
expect_contains(test_guide_text, "tests/account_access/test_account_access_smoke_shinytest2.R", "TEST_GUIDE 账号页 shinytest2 smoke test 文件")
expect_contains(test_guide_text, "tests/statistical_analysis/ui/test_statistical_analysis_layout_guard.R", "TEST_GUIDE 统计分析布局守卫文件")
expect_contains(test_guide_text, "tests/statistical_analysis/ui/test_statistical_analysis_submodule_ui_guard.R", "TEST_GUIDE 统计分析子模块 UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_analysis/ui/test_statistical_analysis_regression_submodule_ui_guard.R", "TEST_GUIDE 统计分析回归类子模块 UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_analysis/ui/test_statistical_analysis_basic_submodule_ui_guard.R", "TEST_GUIDE 统计分析基础检验子模块 UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_analysis/ui/test_statistical_analysis_result_ui_guard.R", "TEST_GUIDE 统计分析结果区 UI 守卫文件")
expect_contains(test_guide_text, "tests/common/ui/test_data_filter_card_ui_guard.R", "TEST_GUIDE data_filter UI 守卫文件")
expect_contains(test_guide_text, "tests/common/ui/test_task_history_card_ui_guard.R", "TEST_GUIDE task_history UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_graphics/ui/test_statistical_graphics_layout_guard.R", "TEST_GUIDE 统计图形入口 UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_graphics/boxplot/test_boxplot_layout_guard.R", "TEST_GUIDE 箱线图外层 UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_graphics/combo/test_combo_layout_guard.R", "TEST_GUIDE 组合图外层 UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_graphics/survival/test_survival_layout_guard.R", "TEST_GUIDE 生存分析外层 UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_graphics/forest/test_forest_layout_guard.R", "TEST_GUIDE 森林图外层 UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_graphics/spider/test_spider_layout_guard.R", "TEST_GUIDE 蜘蛛图外层 UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_graphics/swimmer/test_swimmer_layout_guard.R", "TEST_GUIDE 泳道图外层 UI 守卫文件")
expect_contains(test_guide_text, "tests/statistical_graphics/waterfall/test_waterfall_layout_guard.R", "TEST_GUIDE 瀑布图外层 UI 守卫文件")
expect_contains(test_guide_text, "tests/tables/test_tables_layout_guard.R", "TEST_GUIDE Tables 入口 UI 守卫文件")
expect_contains(test_guide_text, "tests/exploratory_analysis/test_exploratory_analysis_layout_guard.R", "TEST_GUIDE 探索分析入口 UI 守卫文件")
expect_contains(guide_text, "PostgreSQL 隔离 schema 回归测试", "PROJECT_GUIDE PostgreSQL 集成测试策略")
expect_contains(guide_text, "run_auth_regression.ps1", "PROJECT_GUIDE 账号模块统一回归入口")
expect_contains(deployment_text, "docker-compose.local.yml` 或 `docker-compose1.yml` 拉起", "DEPLOYMENT_GUIDE 测试端口说明")
expect_contains(deployment_text, "`docker-compose.local.yml` 现直接读取 `.env.test`", "DEPLOYMENT_GUIDE local compose 读取 .env.test")
expect_contains(deployment_text, "docker-compose1.yml`", "DEPLOYMENT_GUIDE compose1 轻量测试基础设施说明")

expect_contains(spec_text, "系统角色：系统管理员与普通用户两类。", "PROJECT_SPEC 角色口径")
expect_contains(spec_text, "五类组织，全部已落地", "PROJECT_SPEC common 目录分类")
expect_contains(spec_text, "不得读取、浏览或导出其他用户数据空间中的实际数据", "PROJECT_SPEC 服务层保密底线")
expect_contains(spec_text, "普通用户未开通数据空间功能时，仅允许单文件临时上传", "PROJECT_SPEC 临时上传说明")
expect_contains(spec_text, "新注册账号允许先注册并直接登录", "PROJECT_SPEC 邮箱验证说明")
expect_contains(spec_text, "密码重置采用 6 位重置验证码闭环", "PROJECT_SPEC 密码重置说明")
expect_contains(spec_text, "邮箱换绑采用", "PROJECT_SPEC 邮箱换绑说明")
expect_contains(spec_text, "email_service", "PROJECT_SPEC 邮件服务抽象说明")
expect_contains(spec_text, "支持 `console / disabled / smtp` 三种模式", "PROJECT_SPEC SMTP 投递模式说明")
expect_contains(spec_text, "APP_ADMIN_USERNAME`、`APP_ADMIN_EMAIL`、`APP_ADMIN_PASSWORD` 预置，不支持首个注册用户自动升级", "PROJECT_SPEC 管理员初始化")
expect_contains(spec_text, "当前登录态定时刷新用户状态与数据库管理开关", "PROJECT_SPEC 用户会话刷新说明")

expect_contains(deployment_text, "部署相关访问控制要点", "DEPLOYMENT_GUIDE 访问控制边界")
expect_contains(deployment_text, "权限模型与访问控制说明见", "DEPLOYMENT_GUIDE 访问控制引用")
expect_contains(deployment_text, "当前工具暂不负责数据安全", "DEPLOYMENT_GUIDE 免责声明")
expect_contains(deployment_text, "APP_ADMIN_USERNAME", "DEPLOYMENT_GUIDE 管理员环境变量")
expect_contains(deployment_text, "APP_ADMIN_EMAIL", "DEPLOYMENT_GUIDE 管理员邮箱环境变量")
expect_contains(deployment_text, "SMTP_HOST", "DEPLOYMENT_GUIDE SMTP 配置")
expect_contains(deployment_text, "docker-compose.local.yml` 或 `docker-compose1.yml` 拉起", "DEPLOYMENT_GUIDE 测试基础设施")
expect_contains(deployment_text, "轻量测试基础设施栈", "DEPLOYMENT_GUIDE compose1 定位")
expect_contains(deployment_text, "`docker-compose.local.yml` 现直接读取 `.env.test`", "DEPLOYMENT_GUIDE local compose 读取 .env.test")
expect_contains(compose_local_text, '5432:5432', "docker-compose.local PostgreSQL 宿主机测试端口")
expect_contains(compose_local_text, "env_file:", "docker-compose.local 使用 env_file")
expect_contains(compose_local_text, "- .env.test", "docker-compose.local 读取 .env.test")
expect_not_contains(compose_local_text, "APP_ADMIN_USERNAME: \\$\\{APP_ADMIN_USERNAME:-\\}", "docker-compose.local 不再依赖宿主机 APP_ADMIN_USERNAME 插值")
expect_not_contains(compose_local_text, "POSTGRES_PASSWORD: \\$\\{DB_PASSWORD:-ChangeMe123!\\}", "docker-compose.local 不再依赖宿主机 DB_PASSWORD 插值")
expect_contains(deployment_text, "轻量测试基础设施栈", "DEPLOYMENT_GUIDE compose1 定位")
expect_contains(compose_temp_text, "name: autotfl-test-infra", "docker-compose1 compose 名称")
expect_contains(compose_temp_text, "container_name: autotfl-test-infra-postgres", "docker-compose1 PostgreSQL 容器名")
expect_contains(compose_temp_text, "container_name: autotfl-test-infra-redis", "docker-compose1 Redis 容器名")
expect_contains(compose_temp_text, "5432:5432", "docker-compose1 PostgreSQL 宿主机测试端口")
expect_contains(compose_temp_text, "6379:6379", "docker-compose1 Redis 宿主机测试端口")
expect_contains(compose_server_text, "APP_ADMIN_USERNAME", "docker-compose.server 管理员用户名变量")
expect_contains(compose_server_text, "APP_ADMIN_EMAIL", "docker-compose.server 管理员邮箱变量")
expect_contains(compose_server_text, "APP_ADMIN_PASSWORD", "docker-compose.server 管理员密码变量")
expect_contains(env_example_text, "APP_ADMIN_USERNAME=admin", ".env.example 管理员用户名示例")
expect_contains(env_example_text, "APP_ADMIN_EMAIL=admin@example.com", ".env.example 管理员邮箱示例")
expect_contains(env_example_text, "APP_ADMIN_PASSWORD=__CHANGE_ME_ADMIN_PASSWORD__", ".env.example 管理员密码示例")
expect_contains(env_example_text, "AUTH_REQUIRE_EMAIL_VERIFICATION=0", ".env.example 邮箱验证开关")
expect_contains(env_example_text, "EMAIL_DELIVERY_MODE=disabled", ".env.example 邮件投递模式")
expect_contains(env_example_text, "EMAIL_FROM_ADDRESS=noreply@example.com", ".env.example 发件邮箱")
expect_contains(env_example_text, "SMTP_HOST=", ".env.example SMTP_HOST")
expect_contains(env_example_text, "AUTH_PASSWORD_RESET_EXPIRE_MINUTES=30", ".env.example 密码重置过期时间")
expect_contains(test_env_example_text, "APP_ADMIN_USERNAME=admin", ".env.test.example 管理员用户名")
expect_contains(test_env_example_text, "APP_ADMIN_EMAIL=admin@example.com", ".env.test.example 管理员邮箱")
expect_contains(test_env_example_text, "APP_ADMIN_PASSWORD=admin123", ".env.test.example 管理员密码")
expect_contains(test_env_example_text, "AUTH_REQUIRE_EMAIL_VERIFICATION=0", ".env.test.example 邮箱验证开关")
expect_contains(test_env_example_text, "EMAIL_DELIVERY_MODE=console", ".env.test.example 邮件投递模式")
expect_contains(test_env_example_text, "EMAIL_FROM_ADDRESS=autotfl@test.local", ".env.test.example 发件邮箱")
expect_contains(test_env_example_text, "SMTP_HOST=", ".env.test.example SMTP_HOST")
expect_contains(test_env_example_text, "AUTH_DEV_SHOW_EMAIL_CODE=1", ".env.test.example 测试验证码暴露开关")
expect_contains(test_env_example_text, "AUTH_PASSWORD_RESET_EXPIRE_MINUTES=30", ".env.test.example 密码重置过期时间")
expect_contains(test_env_example_text, "POSTGRES_PORT=5432", ".env.test.example 测试端口")
expect_not_contains(readme_text, "首个注册用户会自动成为系统管理员", "README 已移除自动管理员")
expect_not_contains(guide_text, "首个注册用户会自动成为系统管理员", "PROJECT_GUIDE 已移除自动管理员")
expect_not_contains(guide_text, "系统管理员可访问全部 workspace", "PROJECT_GUIDE 已移除管理员全局 workspace 访问口径")
expect_not_contains(spec_text, "全局管理权限", "PROJECT_SPEC 已移除全局管理权限口径")
expect_not_contains(deployment_text, "管理员可访问全部 workspace", "DEPLOYMENT_GUIDE 已移除管理员全局 workspace 访问口径")
expect_not_contains(deployment_text, "首个注册用户自动成为管理员", "DEPLOYMENT_GUIDE 已移除自动管理员")
expect_not_contains(readme_text, "暂不负责数据结果正确", "README 已移除结果正确性免责声明")
expect_not_contains(guide_text, "暂不负责数据结果正确", "PROJECT_GUIDE 已移除结果正确性免责声明")
expect_not_contains(deployment_text, "暂不负责数据结果正确", "DEPLOYMENT_GUIDE 已移除结果正确性免责声明")

cat("Access boundary guard passed.\n")


